charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/README.md, charts/nri-metadata-injection/templates/deployment.yaml, charts/nri-metadata-injection/values.yaml
No
Made the replicas as configurable for `nri-metadata-injection` chart
- fixes #47 
=> [nri-metadata-injection] Make replicas as configurable

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/_helpers.tpl, charts/newrelic-logging/templates/daemonset.yaml
Fixes bug with `nrStaging` when there is no `global` set. I missed this because I was doing my tests using `--set global.licenseKey=zxc` which hid the bug. 
- fixes #
=> [newrelic-logging] fix nrStaging bug when there is no global

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/templates/_helpers.tpl, charts/newrelic-infrastructure/templates/daemonset.yaml
Fixes bug with nrStaging when there is no global set. I missed this
because I was doing my tests using --set global.licenseKey=zxc which hid
the bug.
- fixes #
- [ x] Chart Version bumped
=> [newrelic-infrastructure] Fixes bug with nrStaging

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/values.yaml
no 
Bumps the newrelic-infrastructure charts' appVersion to 1.23.0
=> [newrelic-infrastructure] bumped appVersion to 1.23.0

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/k8s/README.md, charts/newrelic-logging/k8s/fluent-conf.yml, charts/newrelic-logging/k8s/new-relic-fluent-plugin.yml, charts/newrelic-logging/k8s/rbac.yml
No.
It includes the K8s manifests that can be used to install it manually, instead of using Helm. It is required for customers that do not use Helm.
None.
Discussed with @alejandrodnm and @douglascamata
=> [newrelic-logging] Adds Logging K8s manifests for manual (non-helm) installation

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/k8s/fluent-conf.yml, charts/newrelic-logging/k8s/new-relic-fluent-plugin.yml, charts/newrelic-logging/templates/configmap.yaml, charts/newrelic-logging/templates/daemonset.yaml, charts/newrelic-logging/values.yaml
No
Removes buffering-related configuration options from the chart/K8s manifests. These options have been deprecated, and specifying them leads to getting WARN messages, so we have removed them to avoid extra noise.
- Fixes LOGGING-2584.
=> [newrelic-logging] Removes buffering-related configuration parameters

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/_helpers.tpl
no
nri-bundle passes the cluster name as `global.cluster` instead of `global.clusterName`.
=> [newrelic-logging] Added other variant of global clusterName

.github/actions/chart-version-bumper/bump_chart_version.js, .github/actions/chart-version-bumper/bump_chart_version.test.js, README.md
No
It modify the version bumper GHA to increase the chartVersion by 1 if has not been specified.
This way external repos like nri-prometheus could automate the process of updating the app version without knowing the chart version.
- fixes #
=> feat: Auto bump chart version if not specified

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/templates/daemonset-windows.yaml, charts/newrelic-infrastructure/templates/daemonset.yaml
No
It enables configuration of the NRIA_ENABLE_PROCESS_METRICS environment variable for the newrelic-infrastructure agent as described in [the agent configuration docs](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings#enable-process-metrics)
- fixes #141 
=> [newrelic-infrastructure] support configuration of process metrics

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/README.md, charts/nri-metadata-injection/templates/mutationwebhookconfiguration.yaml, charts/nri-metadata-injection/values.yaml
No
Webhooks add to API request latency, they should evaluate as quickly as possible.
Admission webhooks created using `admissionregistration.k8s.io/v1beta1` default timeouts to `30` seconds. This can cause potential problems with the scheduler and block new pods from being created. This is fixed to default to `10` seconds in `admissionregistration.k8s.io/v1`. However, it would be nice to have it configurable to allow for a shorter time or longer if necessary. 
- fixes #
Reference: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts
=> [nri-metadata-injection] Allow support to modify the webhook timeout value

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/README.md, charts/nri-metadata-injection/templates/_helpers.tpl, charts/nri-metadata-injection/templates/deployment.yaml, charts/nri-metadata-injection/templates/job.yaml, charts/nri-metadata-injection/values.yaml
The changes to deployment.yaml allow you to configure a Pod Security Context for the main metadata injector pod so that it doesn't run as root and get denied scheduling
The changes to the job.yaml allow you to configure mounts in the Pod so that /tmp can be mounted as an emptydir when policy enforces a read-only root filesystem.
Additional Values added to values.yaml
README.md updated with new configuration values
Chart version bumped.
Fixes #122
No
So that the metadata injector can run in more restrictive environments
- fixes #122
=> [nri-metadata-injection] Changes to support running newrelic metadata injector in Kubernetes clusters with restrictive Pod Security Policy.

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/README.md, charts/newrelic-logging/templates/configmap.yaml, charts/newrelic-logging/templates/daemonset.yaml, charts/newrelic-logging/values.yaml
No
This adds a value configuration so we can configure the `K8S-Logging.Exclude` part of FluentBit. The [new relic blog post](https://blog.newrelic.com/engineering/disable-new-relic-logging-for-kubernetes/) explains how this needs to be turned on in order for FluentBit to ignore certain pods with the annotation `fluentbit.io/exclude: "true"`
@bmcfeely 
@jsubirat 
@matildasmeds
@tejunior
=> [newrelic-logging] Add value to control fluentd k8s-logging.exclude configuration

charts/newrelic-logging/Chart.yaml
A PR was rebased and we did not notice that the commit didn't have anymore the chart version bump needed
https://github.com/newrelic/helm-charts/commit/2bf6a9543df4d27b8b8475acbb618a8b49edc508
This caused the CI/CD to fail and the chart not to be released
=> [newrelic-logging] bumping chart version

charts/nri-kube-events/Chart.yaml, charts/nri-kube-events/README.md, charts/nri-kube-events/templates/deployment.yaml, charts/nri-kube-events/values.yaml
No
- Makes the `runAsUser` parameter configurable
N/A
N/A
=> [nri-kube-events]: added configurable runAsUser

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/templates/NOTES.txt, charts/newrelic-infrastructure/templates/daemonset.yaml, charts/newrelic-infrastructure/values.yaml
No
- Added `openshift` parameter which enables `/var/run/crio.sock` and auto-enables Control Plane endpoints
- Added a comment and docs links about ETCD mTLS (the parameters were already there previously)
- Made runAsUser configurable. Previously, it was statically set in the daemonset.yaml file.
- Updated the README with the new parameters
N/A
N/A
=> [newrelic-infrastructure]: Added OpenShift parameter and other minor updates

charts/nri-kube-events/Chart.yaml, charts/nri-kube-events/README.md, charts/nri-kube-events/templates/deployment.yaml, charts/nri-kube-events/values.yaml
No
Infra-agent / Kube forwarder connects to New Relic One endpoint over the
internet. Hence, some of us require proxy to be set for this to work
- fixes #
=> [nri-kube-events] - Infra-agent / Kube forwarder connects to New Relic One endpoint over the

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/templates/daemonset.yaml, charts/newrelic-infrastructure/values.yaml
no
The configuration was a bit misleading and could lead a customer running a 3.x openshift to enable configuration needed by 4.x only
Fix https://github.com/newrelic/helm-charts/issues/192
=> [newrelic-infrastructure] Some options should be enabled for some versions only

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/k8s/fluent-conf.yml, charts/newrelic-logging/templates/configmap.yaml
No
In [this PR](https://github.com/newrelic/helm-charts/pull/165/files), the `newrelic-fluent-bit-output` plugin [Docker generated image](https://github.com/newrelic/newrelic-fluent-bit-output/blob/master/Dockerfile) version was increased from `1.3.0` to `1.4.3`. These versions use the pre-compiled FluentBit Docker image as starting point, [with versions 1.0.3 and 1.6.2 respectively](https://github.com/newrelic/newrelic-fluent-bit-output/compare/1.3.0...1.4.3#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R15).
We didn't detect, though, that Fluent Bit introduced a breaking change between these versions: the `Merge_JSON_Log` property from the `kubernetes` plugin, which [was available](https://fluentbit.io/documentation/0.11/filter/kubernetes.html) in Fluent Bit …
=> [newrelic-logging] LOGGING-3799 Fix deprecated Merge_JSON_Log option

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/README.md, charts/nri-metadata-injection/templates/cert-manager.yaml, charts/nri-metadata-injection/templates/clusterrole.yaml, charts/nri-metadata-injection/templates/clusterrolebinding.yaml, charts/nri-metadata-injection/templates/deployment.yaml, charts/nri-metadata-injection/templates/job.yaml, charts/nri-metadata-injection/templates/mutationwebhookconfiguration.yaml, charts/nri-metadata-injection/templates/serviceaccount.yaml, charts/nri-metadata-injection/values.yaml
No
Add cert-manager support for webhook. We use cert-manager for all our other validating/mutating webhooks, so it makes sense for newrelic to also support this.
=> [nri-metadata-injection] cert-manager support for webhook

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/k8s/fluent-conf.yml, charts/newrelic-logging/templates/configmap.yaml
This PR fix a JSON parsing issue. 
The removed log line `Decode_Field_As   escaped    log` makes that fluentbit submit to NewRelic a not valid JSON. This line get a valid escaped JSON (that was escaped by Kubernetes) and convert into the real char. (eg. `\n` will be converted in the real brake line)
- fixes #
=> [LOGGING-3985] Fix Json parsing issue

charts/nri-prometheus/Chart.yaml, charts/nri-prometheus/values.yaml
No
- Updated the POMI image tag from 2.2.0 to 2.3.1
- Updated the values.yaml config section to include all config options including an updated `ignore_metrics` list.  A lot of this was previously missing.
N/A
Closed out [#232](https://github.com/newrelic/helm-charts/pull/232) in favor of this one.
=> [nri-prometheus] Updated image to 2.3.1, all config options, and updated ignore_metrics

charts/nri-prometheus/Chart.yaml, charts/nri-prometheus/values.yaml
Nope
Adds advanced configuration flags to `nri-prometheus`'s `values.yml`. Please note that changing this values can affect CPU and Memory consumption in unforeseen ways. We recommend to exercise care when changing `worker_threads`, and not to modify other flags unless instructed by the New Relic support team, as the default values cover the vast majority of use cases.
- (N/A) Variables are documented in the README.md
---
Related https://github.com/newrelic/nri-prometheus/issues/130
=> nri-prometheus: add advanced config flags to values

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/README.md, charts/nri-metadata-injection/values.yaml
This PR updates the Job image of [nri-metadata-injection] in order to support k8s 1.19
- https://github.com/newrelic/k8s-metadata-injection/releases/tag/v1.3.2
- https://github.com/newrelic/k8s-webhook-cert-manager/releases/tag/v1.3.2
=> [nri-metadata-injection]: Updating job image to support k8s 1.19

charts/nri-prometheus/Chart.yaml, charts/nri-prometheus/values.yaml
No
Increases example resource limits for nri-prometheus, as we have seen [before](https://github.com/newrelic/nri-prometheus/issues/132) that 128Mi might not be enough for it to successfully scrape targets with many metrics, as K8S control planes.
https://github.com/newrelic/nri-prometheus/issues/132
=> [nri-prometheus]: suggestively increase commented resources

charts/nri-prometheus/Chart.yaml, charts/nri-prometheus/values.yaml
No
The configuration option can be set using the command line but because it's not visible in the chart, customers (and support) are not aware that it can be changed
=> [nri-prometheus] Make metric_api_url visible for configuration.

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/values.yaml
no
Improve the documentation for enableProcessMetrics showing a workaround to set enableProcessMetrics = `"false"`
Basically helm template is not able to recognize the difference between the logical false, 0 and nil. Therefore if set to `false` that config will be considered as not set and the `NRIA_ENABLE_PROCESS_METRICS` not injected. Therefore we need to pass it as a string
- fixes https://github.com/newrelic/helm-charts/issues/285
=> [newrelic-infrastructure] Improve enableProcessMetrics

.codespellrc, .github/workflows/bump_chart_version.yaml, .github/workflows/lint_test_charts.yaml, charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/values.yaml, charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/values.yaml, charts/nri-kube-events/Chart.yaml, charts/nri-kube-events/values.yaml, charts/nri-prometheus/Chart.yaml, charts/nri-prometheus/values.yaml, charts/synthetics-minion/Chart.yaml, charts/synthetics-minion/values.yaml
No.
Fixes typos and adds spell checking as part of CI process.
Not sure if this is going to work. If not, I'll split into multiple PRs.
=> Fix various typos and add spellchecking to CI

charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml, charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/templates/job.yaml
No
This PR appends 6 random alphanumeric characters (considered enough to provide unicity) to the job charged with signing certificates for the metadata injection.
This allows upgrades to proceed smoothly when the image of container ran in the job is updated, which would otherwise fail as the pod inside a job is immutable.
- Fixes #248
- Fixes #280
=> [nri-metadata-injection] append random characters to job name

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/templates/daemonset.yaml, charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
No
Previously, if the user defined `enableProcessMetrics` to `false`, it wouldn't be printed into the template. This could be workarounded by definining it as `"false"` in the values file, but this is not possible from the command line with `--set`.
This PR implements an alternative (and perhaps rather hacky) approach to detect an undefined `.Values.enableProcessMetrics`.
Any less hacky solution is welcome.
=> [newrelic-infrastructure] better detection for enableProcessMetrics

charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
this version introduces kube-webhook-certgen as the way to generate webhook certificates
No
Incorporates kube-webhook-certgen  1.4.2 (#334) into the bundle.
=> [nri-bundle] upgrade nri-metadata-injection to 1.4.2

charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
No.
Updates the version of newrelic-pixie chart in the bundle to 0.1.0-alpha.2
=> [nri-bundle] Bump up newrelic-pixie chart to 0.1.0-alpha.2

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/templates/NOTES.txt, charts/newrelic-infrastructure/templates/_helpers.tpl, charts/newrelic-infrastructure/templates/daemonset.yaml
Despite being a convention, .Values.global is not automatically initialized to anything. When trying to render this chart alone, attempting to check for truthyness of .Values.global.fargate caused a NPD.
This commit adds a helper similar to newrelic.nrStaging taking care of checking if .Values.global is defined before attempting to deference it.
Nope
=> [newrelic-infrastructure] fix NPD in .Values.global

charts/newrelic-pixie/Chart.yaml
No
Update to the latest version of the Pixie integration.
Adds data limiting options in v0.1.6 of the integration.
=> [newrelic-pixie] Update to the latest version for the Pixie integration.

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/values.yaml
No 
As we expect an array here, not map and while definiting it as array,
Helm prints the following warning:
coalesce.go:200: warning: cannot overwrite table with non table for
integrations_config (map[])
This PR fixes that.
- Closes #405
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
=> [newrelic-infrastructure] Set integrations_config default value to []

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/k8s/new-relic-fluent-plugin.yml
No
This updates the newrelic fluent bit output plugin docker image version from 1.4.6 to 1.6.1 which implies fluent bit 1.8.1 
=> [newrelic-logging] Bump fluent bit output plugin docker image version

charts/nri-kube-events/Chart.yaml, charts/nri-kube-events/templates/deployment.yaml
no
Replace the secure forward mode for the forward only mode to avoid entity creation and collision. 
- fixes https://github.com/newrelic/nri-kube-events/issues/56
Staging test [link](https://staging-one.newrelic.com/-/0nVjYPGbXR0)
Also [check](https://staging-one.newrelic.com/-/01qwL5LXgR5) that cluster explorer still has the same functionality regarding the events and linkage to the entities that they belong. 
=> [nri-kube-events] Use the NRIA_IS_FORWARD_ONLY to avoid entity collision.

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/templates/deployment.yaml
Thanks @ghostsquad for noticing that, even if it is only an info it is best practice to add that:
```
RESOURCE: ports <[]Object>
DESCRIPTION:
List of ports to expose from the container. Exposing a port here gives the
system additional information about the network connections a container
uses, but is primarily informational. Not specifying a port here DOES NOT
prevent that port from being exposed. Any port which is listening on the
default "0.0.0.0" address inside a container will be accessible from the
network. Cannot be updated.
```
no
- fixes https://github.com/newrelic/helm-charts/issues/441
=> [nri-metadata-injection] adding missing port info

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/templates/_helpers.tpl, charts/newrelic-infrastructure/templates/daemonset-windows.yaml, charts/newrelic-infrastructure/templates/daemonset.yaml
No
Fixes a regression introduced in #421 which caused upgrade to fail if `--reuse-values` were specified in the CLI.
=> newrelic-infrastructure: make updateStrategy backwards-compatible

charts/newrelic-logging/Chart.yaml
No.
Updates the `newrelic-logging` Helm chart to use the `1.8.0` version of the image, which adds support for multiarchitecture images.
* Adds support for multiarchitecture images by using the latest 1.8.0 image version (appVersion)
=> [newrelic-logging] Update newrelic-logging to appVersion 1.8.0 to support multiarchitecture image

charts/newrelic-pixie/Chart.yaml, charts/newrelic-pixie/README.md, charts/newrelic-pixie/templates/deployment.yaml, charts/newrelic-pixie/values.yaml
No
It adds a proxy configuration field to the Pixie integration Helm chart.
=> [newrelic-pixie] Add proxy configuration for Pixie integration.

charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
No.
Bump the nri-bundle chart to the latest version of the newrelic-integration chart version.
* Trace database request on the client side only.
=> [nri-bundle] Update newrelic-pixie to the latest version

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/k8s/new-relic-fluent-plugin.yml
No.
Updates docker image version in newrelic-logging K8s manifest (not in the Helm chart, just the raw manifests). There is no need to bump the chart version due to this commit, since it doesn't affect the Helm chart at all.
- Updates version in logging K8s manifest.
=> [newrelic-logging] Update version in logging K8s manifest to 1.8.0

.github/renovate.json5
Seems like the `helm-requirements` module for Renovate does not support updating the `requirements.lock` file, which our CI and workflow requires.
This PR disables that feature to avoid noise.
Docker image bumping should still work, although might require manual intevention.
Theoretically this should not be a problem with the Helm v3 module.
=> renovate: disable bumping requirements as renovate does not support updating lockfile

.github/workflows/release.yml
Previously, merging two PRs to `master` at the same time (or very close in time) might cause two `Release` workflows to trigger in parallel. Since the release is done by pushing to the `gh-pages` branch, which is shared, a write-after-read race might occur, resulting in one of the releases failing or overwriting the other one.
This PR sets the `concurrency` key of the release workflow to instruct GHA to allow only one parallel run of said workflow.
=> ci: prevent concurrent releases

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/templates/daemonset-windows.yaml
No
Fixes an error where the `updateStrategy` helper was not being called with the right argument in the daemonset-windows template.
=> newrelic-infrastructure: fix use of updateStrategy in daemonset-windows

charts/newrelic-pixie/Chart.yaml, charts/newrelic-pixie/README.md, charts/newrelic-pixie/templates/_helpers.tpl, charts/newrelic-pixie/templates/deployment.yaml, charts/newrelic-pixie/values.yaml
No
* Bump the Pixie integration version to 1.4.0
* Introduces low data mode
* Communication to Pixie now uses end-to-end encryption
* OTLP protobuf updated to v0.9.0
=> [newrelic-pixie] Introducing low data mode & bump to v1.4.0

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset.yaml
No
The logging container reads logs directly from the host's `/var` directory, for performance reasons. However, there is no reason to grant this deployment write privileges to this directory.
Flagging this as read-only reduces potential attack surface and should also allow deploying the logging solution in K8s environments with tighter security policies, such as GKE Autopilot.
This is still pending some tests.
=> newrelic-logging: mount host's /var as read only

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset.yaml
It seems like FluentBit will refuse to start up if it cannot create a database in `/var/log/flb_kube.db`.
This reverts commit 47a199872643602337fe05a94cb037d912812199.
=> Revert "newrelic-logging: mount host's /var as read only (#472)"

charts/newrelic-infra-operator/Chart.yaml, charts/newrelic-infrastructure/Chart.yaml, charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml, charts/nri-kube-events/Chart.yaml, charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/clusterrole.yaml, charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml, charts/nri-metadata-injection/values.yaml, charts/nri-prometheus/Chart.yaml
This PR *introduces Kubernetes 1.22.x* support for the New Relic Kuberentes solution, and *removes support for kubernetes 1.15.x and below*.
Users may still use previous versions of the `nri-bundle` and other charts to instrument their clusters, and limited support will be offered for them. Development for said older versions is considered stopped and New Relic does guarantee feature parity or bugfixes (security or otherwise) for those older versions.
No
Bumps versions in individual charts and the bundle to point to the latest released versions of all Kubernetes components, which include support for Kubernetes 1.22.
Additionally, some changes to the charts themselves are also included to make them compatible with said version.
[Place an '[x]' (no spaces) in all applicable fields. Please …
=> nri-bundle: Add Kubernetes 1.22 support

charts/newrelic-pixie/Chart.yaml
No
It updates the Pixie integration to v1.4.1 fixing a high cpu usage issue with the end-to-end encryption.
=> [newrelic-pixie] Update to the v1.4.1 of the integration

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/configmap.yaml
When docker is used log messages are wrapped in the log attribute
When CRI is used log messages are wrapped in the message attribute
We need both to in the Allowlist_key
- fixes Low Data Mode to allow logs. 
=> [newrelic-logging] Fixes config map to not exclude message when running in lowDataMode (docker & cri)

charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
No
Bump version of nri-bundle
the bundle includes now newrelic-logging 1.10.3
=> [nri-bundle] Bump version to 3.2.7 including newrelic-logging 1.10.3

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/README.md, charts/newrelic-logging/templates/_helpers.tpl, charts/newrelic-logging/templates/configmap.yaml, charts/newrelic-logging/values.yaml
No
The changes in this PR provide users the ability to customize the fluent-bit.conf and parsers.conf files using the values.yaml file. Previously, this was statically set in the configmap.yaml file. This will provide much better flexibility for custom fluent-bit configurations.
A cleanup and continuation of https://github.com/newrelic/helm-charts/pull/551 (previously closed by me).
=> [newrelic-logging] Made fluent-bit.conf and parsers.conf ConfigMap configurable from values.yaml file

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/ci/test-enable-windows-values.yaml, charts/newrelic-logging/ci/test-lowdatamode-values.yaml, charts/newrelic-logging/ci/test-staging-values.yaml, charts/newrelic-logging/templates/daemonset-windows.yaml, charts/newrelic-logging/templates/daemonset.yaml, charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
No.
In the PR #593 a bug to this chart was introduced because there is not enough ci testing at your chart level, so now that we are trying to bump `nri-bundle` this chart is failing.
This PR try to add some testing while only this chart is being modified.
=> [newrelic-logging] Add testing to newrelic logging chart

charts/newrelic-infrastructure-v3/Chart.yaml, charts/newrelic-infrastructure-v3/README.md, charts/newrelic-infrastructure-v3/README.md.gotmpl, charts/newrelic-infrastructure-v3/templates/control-plane/configmap.yaml, charts/newrelic-infrastructure-v3/templates/control-plane/daemonset.yaml, charts/newrelic-infrastructure-v3/templates/ksm/configmap.yaml, charts/newrelic-infrastructure-v3/templates/ksm/deployment.yaml, charts/newrelic-infrastructure-v3/templates/kubelet/configmap.yaml, charts/newrelic-infrastructure-v3/templates/kubelet/daemonset.yaml, charts/newrelic-infrastructure-v3/values.yaml
This PR adds some documentation to the values.yml file, and makes use of https://github.com/norwoodj/helm-docs to autogenerate a README.md file with documentation from the same `values.yml` file and `README.md.gotmpl`.
To regenerate this README.md again, just run `helm-docs`:
- `go run github.com/norwoodj/helm-docs/cmd/helm-docs`
- `docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest`
Closes #635
=> newrelic-infrastructure-v3: document values, generate README.md

charts/newrelic-infrastructure-v3/Chart.yaml, charts/newrelic-infrastructure-v3/README.md, charts/newrelic-infrastructure-v3/templates/NOTES.txt, charts/newrelic-infrastructure-v3/templates/control-plane/_helpers.tpl, charts/newrelic-infrastructure-v3/templates/control-plane/daemonset.yaml, charts/newrelic-infrastructure-v3/values.yaml
Previously, if `privileged` was set to `false`, we deployed the control plane DaemonSet with `hostNetwork: false`. However, this will almost certainly cause it not to work as intended.
This PR:
- Adds a way to deploy the DaemonSet with `hostNetwork: true` even when `privileged: false` (disabled by default)
- Warns the user and encourages them to set this flag if control plane monitoring is enabled
=> newrelic-infrastructure-v3: add a separate hostNetwork toggle for control plane monitoring

charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
No
Updates the `nri-bundle` with the most recent `nri-prometheus` chart version.
=> [nri-bundle] Bump nri-prometheus version in nri-bundle

charts/newrelic-pixie/Chart.yaml
No
It updates the Pixie integration to v1.4.3 that uses port 443 for the New Relic OTel endpoint
=> [newrelic-pixie] Update to v1.4.3 of the integration

charts/newrelic-infrastructure-v3/Chart.yaml, charts/newrelic-infrastructure-v3/README.md, charts/newrelic-infrastructure-v3/ci/test-cplane-kind-deployment-values.yaml, charts/newrelic-infrastructure-v3/ci/test-values.yaml, charts/newrelic-infrastructure-v3/templates/kubelet/daemonset.yaml, charts/newrelic-infrastructure-v3/values.yaml
no
Since hostnetwork is false now NRIA_HOST is needed. (read by the the discovery binary)
We removed the Cluster_name env var and the passthrough to the integration but it was still needed  
=> [newrelic-infrastructure-v3] Adding needed variable for autodiscovery

charts/newrelic-infrastructure-v3/Chart.yaml, charts/newrelic-infrastructure-v3/templates/NOTES.txt, charts/newrelic-infrastructure-v3/tests/interval_override_test.yaml, charts/newrelic-infrastructure-v3/tests/interval_test.yaml
Causes the chart to fail to render if `common.config.interval` is not in the `[10, 45]s` range.
This check can be overridden by setting the undocumented and unsupported flag `forceUnsupportedInterval` to `true`.
=> newrelic-infrastructure-v3: restrict interval to [10, 45]s

charts/newrelic-infrastructure-v3/Chart.yaml, charts/newrelic-infrastructure-v3/templates/agent-configmap.yaml, charts/newrelic-infrastructure-v3/templates/controlplane/daemonset.yaml, charts/newrelic-infrastructure-v3/templates/ksm/deployment.yaml, charts/newrelic-infrastructure-v3/templates/kubelet/daemonset.yaml, charts/newrelic-infrastructure-v3/templates/kubelet/integrations-configmap.yaml, charts/newrelic-infrastructure-v3/tests/annotations_test.yaml, charts/newrelic-infrastructure-v3/tests/configmap_agent_test.yaml, charts/newrelic-infrastructure-v3/tests/configmap_integrations_test.yaml, charts/newrelic-infrastructure-v3/tests/nodeAffinity_test.yaml, charts/newrelic-infrastructure-v3/tests/nodeSelectors_test.yaml, charts/newrelic-infrastructure-v3/tests/podName_test.yaml, charts/newrelic-infrastructure-v3/tests/securityContext_test.yaml
Previously, we completely skipped config maps and their respective mounts if the agent config or the integrations config was empty. This was done to reduce clutter and unnecessary objects in the clusters where the chart is deployed.
However, while working on the docs (https://github.com/newrelic/docs-website/pull/5742), I realized that for installations using the generated manifests (which we support) we point users to modify or add items to these configmaps. If the configmaps do not exist, it would be hard for users  to create them and mount them in the correct places.
For this reason, this PR makes these manifests to render unconditionally, and adds some comments and examples on them.
=> newrelic-infrastructure-v3: render integrations and agent configmaps unconditionally

.github/workflows/lint_test_charts.yaml
Mostly as the title says. There should not be any reason for it being in the same job as the lint/test flow.
=> ci: split codespell to a separate job

.github/workflows/pr_index_integrity.yaml, index.yaml
Publishing new release currently available in fork repo only.
To test that:
```
helm repo add newrelic-beta https://newrelic-forks.github.io/helm-charts
helm upgrade --install newrelic-bundle-beta newrelic-beta/nri-bundle --devel
helm search repo newrelic --devel
```
=> [gh-pages] update manually index to include beta release

charts/newrelic-infrastructure-v3/Chart.yaml, charts/newrelic-infrastructure-v3/templates/NOTES.txt, charts/newrelic-infrastructure-v3/templates/_helpers_compatibility.tpl
no
- `--reuse-values` is not allowed when migrating from V2 to V3. It is specified into the docs, however it was not super clear at update time.
- Moreover I refactor a bit the errors adding a link to docs:
```
Error: UPGRADE FAILED: execution error at (nri-bundle/charts/newrelic-infrastructure/templates/NOTES.txt:133:4):
######
The chart cannot be rendered since the values listed below are not supported. Please replace those with the new ones compatible with newrelic-infrastructure V3.
Keep in mind that the flag "--reuse-values" is not supported when migrating from V2 to V3.
Further information can be found in the official docs https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3#migration-guide"
######
You have specified the legacy …
```
=> [newrelic-infrastructure-v3] improved error messages

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/flex/nri-pixie-check.yaml, charts/newrelic-infrastructure/templates/configmap.yaml, charts/newrelic-infrastructure/templates/daemonset.yaml, charts/newrelic-infrastructure/values.yaml
No
Adds the `flex/nri-pixie-check.yaml` flex config to the `newrelic-infra-integrations-cfg` configMap.  This provides users the ability to query the status of Pixie health check endpoints using `pixieHealthCheck` custom events.
N/A
=> [newrelic-infrastructure] Adding nri-flex config for Pixie cloud connector health and status checks

.github/ct-install.yaml, .github/workflows/lint_test_charts.yaml
No
We introduced a regression in the PR #713 that broke the tests but only for change in `nri-bundle` helm chart.
A log can be seen here: https://github.com/newrelic/helm-charts/runs/5430202040?check_suite_focus=true#step:7:23
But I copy and paste it here in case Github rotates the logs:
```
Run ct lint --config .github/ct-lint.yaml
Linting charts...
------------------------------------------------------------------------------------------------------------------------
Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
nri-bundle => (version: "3.4.0", path: "charts/nri-bundle")
------------------------------------------------------------------------------------------------------------------------ …
```
=> Fix chart linting

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/tests/common_library_serviceaccount_name_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_serviceaccount.tpl
When setting a .values service account name should take precedence to the default one
=> [common-library] Fix local service account name

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/config-map-of-examples.yaml, library/CHART-TEMPLATE/templates/example-cm-lowdatamode.yaml, library/CHART-TEMPLATE/tests/common_library_lowdatamode_test.yaml, library/common-library/Chart.yaml
No
We merged `common-library` with support for `lowDataMode` but it has neither unit testing nor example.
This PR adds it.
=> [common-library] Add a testing suite for lowDataMode

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/deployment.yaml, library/CHART-TEMPLATE/tests/common_library_dnsconfig_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_dnsconfig.tpl
No
We still have to adapt all the helm charts to use this but this allows us to change `dnsConfig` through all our helm charts.
- Fixes #589
=> [common-library] Add dnsConfig feature to the common library

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/deployment.yaml, library/CHART-TEMPLATE/tests/common_library_hostnetwork_test.yaml, library/CHART-TEMPLATE/values.yaml, library/common-library/Chart.yaml, library/common-library/templates/_hostnetwork.tpl
No
This adds to chart template and common library the ability to set `hostNetwork` to the pods.
=> [common-library] Add host network helper

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/tests/common_library_serviceaccount_create_test.yaml, library/CHART-TEMPLATE/tests/common_library_serviceaccount_name_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_serviceaccount.tpl
No
We normally use `serviceAccount` for our needs so we should have them enabled by default if there is nothing in the values. This changes the default before we go GA so we do not break everything.
=> [common-library] Change service account creation default to true

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/deployment.yaml, library/CHART-TEMPLATE/templates/example-cm-licensekey.yaml, library/CHART-TEMPLATE/templates/example-secret.yaml, library/CHART-TEMPLATE/tests/common_library_license_helpers_test.yaml, library/CHART-TEMPLATE/tests/common_library_license_secret_test.yaml, library/CHART-TEMPLATE/values.yaml, library/common-library/Chart.yaml, library/common-library/templates/_license.tpl, library/common-library/templates/_license_secret.yaml.tpl
The following helper functions have been added to the common library:
- `common.license.secretName`, returing the name of the secret holding the license key.
- `common.license.secretKeyName`, returing name of the key inside the secret containing the license key.
- `common.license.secret`, which renders a secret if and only if user supplies the license key ad-hoc in the values.
All the logic of handling both globals _and_ custom secret names for the keys are already implemented in the helpers above, so chart writers only have to do two things:
1, include the `common.licenseKey.secret` template:
```
───────┬───────────────────────────────────────────────────────────────────────
│ File: example-secret.yaml
│ Size: 44 B
───────┼────────────────────────────────────────────────────────────────── …
```
=> common-library: add licenseKey related helpers

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/example-cm-privileged.yaml, library/CHART-TEMPLATE/tests/common_library_privileged_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_privileged.tpl
This PR implements the `common.privileged` helper.
As stated in the comments, all the logic of handling how this flag impacts settings such as `hostNetwork` or the pod and container `securityContext`s is deliberately left out from the common library, and instead Chart writers are expected to use `common.privileged` to define their default overrides for the mentioned settings.
I have two reasons to believe this is a better option than trying to implement this in the library:
1. We only have one chart (two, if you count logging, but its special so refer to point 2) that uses the privileged mode. I believe we should only implement common things in the common library and logic used by one chart is not common.
2. Charts that require the privileged flag require it because they do weird things. …
=> common-library: implement privileged helper

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/example-cm-licensekey.yaml, library/CHART-TEMPLATE/templates/example-cm-lowdatamode.yaml, library/CHART-TEMPLATE/templates/example-cm-staging.yaml, library/CHART-TEMPLATE/tests/common_library_staging_test.yaml, library/common-library/Chart.yaml
No
This adds tests for the `staging` helper that was merged on the very first PR of this library without unit tests.
=> [common-library] Add tests for nrStaging

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/common-library/Chart.yaml, library/common-library/templates/_naming.tpl
No
The function that overrides the chart name was implemented but not used in `common.naming.fullname` function.
=> [common-library] Fix template naming

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/deployment.yaml, library/CHART-TEMPLATE/templates/example-cm-hostnetwork.yaml, library/CHART-TEMPLATE/tests/common_library_hostnetwork_cm_test.yaml, library/CHART-TEMPLATE/tests/common_library_hostnetwork_deployment_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_hostnetwork.tpl
No
`hostNetwork` was not correctly developed and printed `false` when being called. A new test, template and function have been added to solve this issue.
=> [common-library] Fix hostNetwork default behavior

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/example-cm-hostnetwork.yaml, library/CHART-TEMPLATE/templates/example-cm-verbose.yaml, library/CHART-TEMPLATE/tests/common_library_hostnetwork_cm_test.yaml, library/CHART-TEMPLATE/tests/common_library_verbose_test.yaml, library/CHART-TEMPLATE/values.yaml, library/common-library/Chart.yaml, library/common-library/templates/_verbose-log.tpl, library/common-library/templates/_verbose.tpl
No
This allows toggling the debug verbosity consistently in all the Helm charts that use this library
=> [common-library] Add verbose flag

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/tests/common_cluster_test.yaml, library/CHART-TEMPLATE/tests/common_images_security_context_container_test.yaml, library/CHART-TEMPLATE/tests/common_images_security_context_pod_test.yaml, library/CHART-TEMPLATE/tests/common_library_fedramp_test.yaml, library/CHART-TEMPLATE/tests/common_library_hostnetwork_deployment_test.yaml, library/CHART-TEMPLATE/tests/common_library_lowdatamode_test.yaml, library/CHART-TEMPLATE/tests/common_library_privileged_test.yaml, library/CHART-TEMPLATE/tests/common_library_proxy_test.yaml, library/CHART-TEMPLATE/tests/common_library_serviceaccount_annotations_test.yaml, library/CHART-TEMPLATE/tests/common_library_staging_test.yaml, library/CHART-TEMPLATE/values.yaml, library/common-library/Chart.yaml, library/common-library/templates/_cluster.tpl
No
`cluster` helper gets cluster correctly but does not fail when it is not defined. Charts using this library should rely on helpers who will always give the value they need. 
If you feel a bit overwhelmed by the number of changes go commit by commit as I also sanitized the tests in this PR removing useless things that they were not working.
=> [common-library] Fail when no cluster name is given by the user

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/tests/common_library_license_helpers_test.yaml, library/CHART-TEMPLATE/tests/common_library_naming_test.yaml, library/CHART-TEMPLATE/tests/common_library_serviceaccount_create_test.yaml, library/CHART-TEMPLATE/tests/common_library_serviceaccount_name_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_naming.tpl
no
Previous to this the fullname of resources had a logic to add the `nri-` prefix and use release name if collisions with the chart name.
The goal of this was to standardize naming across different charts but more logic should have been needed to cover cases like chart starting with `nri-` or `newrelic` to avoid replications in the name.
But since all charts using the library will be using the common naming helpers , the standardization will take place anyway and all charts will start with the release name, followed by the chart name.
- fixes #
=> [common-library] Removes chartnameOverride and simplify full naming logic

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/common-library/Chart.yaml, library/common-library/templates/_naming.tpl
No
There is an issue in the `naming.fullname` function where we do not test if `Release` was in the name or not at concatenate it.
It is an idiomatic behavior that `helm` creates while `helm create example-chart`.
This PR also adds a useful function to truncate long names
=> fix fullname to ensure that the release name is included

charts/nri-bundle/Chart.yaml, charts/nri-bundle/requirements.lock, charts/nri-bundle/requirements.yaml
Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>
No
This updates Pixie's operator version, to pull in some operator helm chart changes which allow users to further customize the memory usage of Pixie.
None
=> [nri-bundle] Bump Pixie operator version to 0.0.24

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/templates/job.yaml, library/CHART-TEMPLATE/tests/common_library_naming_suffix_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_naming.tpl
Include a naming helper to handle names with prefixes. See potential usage example [here](https://github.com/newrelic/k8s-metadata-injection/blob/bb45f8a0c1d49fd47fa96bb95cd14b8603ce327f/charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml#L5)
=> common.library: include helper to handle dns-valid names with suffixes

charts/nri-bundle-legacy/Chart.yaml
No
The pipeline is failing this error:
```
Error: error creating GitHub release nri-bundle-3.6.2: POST https://api.github.com/repos/newrelic/helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
It is true, it already exists.
Charts that were already tagged but there is no update in the `gh-pages` branch so I had to delete them manually:
```shell
git push --delete origin newrelic-infra-operator-0.6.1
git push --delete origin newrelic-infrastructure-2.10.1
git push --delete origin newrelic-k8s-metrics-adapter-0.3.3
```
So in the next run everything should be tagged and released properly.
=> [nri-bundle-legacy] Fix stuck CI pipeline

charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml
No.
We have a couple of PRs pending from renovate bot that I would like to merge in the same PR as it still is not able to bump the version of the `nri-bundle` chart.
=> [nri-bundle] Update dependencies

charts/nri-bundle-legacy/Chart.yaml
No.
The CI didn't see any conflict because a previous PR did the same change. so we finished with a changed chart with an already released version: 
> `Error: error creating GitHub release nri-bundle-3.6.4: POST https://api.github.com/repos/newrelic/helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]`
=> [ci/cd] Fix stuck CI

charts/nri-bundle-legacy/Chart.yaml, charts/nri-bundle-legacy/requirements.lock, charts/nri-bundle-legacy/requirements.yaml, charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml, charts/nri-bundle/README.md
No.
- Updates `nri-bundle-legacy` from 3.6.5 to 3.6.6
- `newrelic-infrastructure` changes its upstream to https://newrelic.github.io/nri-kubernetes 
- `newrelic-infrastructure` upgrades its chart version from `2.10.1` to `2.10.3`
- Updates `nri-bundle` from 4.4.5 to 4.4.6
- `newrelic-infrastructure` upgrades its chart version from `3.3.4` to `3.3.6`
- `nri-metadata-injection` upgrades its chart version from `3.0.3` to `3.0.4`
- `nri-kube-events` upgrades its chart version from `2.2.3` to `2.2.4`
- `newrelic-infra-operator` upgrades its chart version from `1.0.2` to `1.0.3`
Fixes #818
=> [nri-bundle] Update bundle dependencies

.github/renovate.json5
No.
This should add `nri-bundle-legacy` to the list of charts to be automatically updated.
=> [ci/cd] Include legacy chart in the renovate rules

.github/ct-install.yaml, .github/ct-lint.yaml, .github/workflows/release.yml
No
Fix pipeline to add missing helm chart origin. Tests are failing on the PR #762. This change should fix it.
=> [CI/CD] Fix pipeline to add missing origin

charts/nri-bundle/Chart.yaml, charts/nri-bundle/README.md, charts/nri-bundle/values.yaml
no
In order to remove an annoying log from KSM:
```
I0524 07:33:23.082532       1 builder.go:146] Active collectors: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
E0524 07:33:23.150180       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.CertificateSigningRequest: the server could not find the requested resource
E0524 07:33:23.165645       1 …
```
=> [nri-bundle] removing collector to address noisy log

charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml, charts/nri-bundle/README.md, charts/nri-bundle/values.yaml
No
It changes the UX on how to enable and configure the charts.
From:
```yaml
infrastructure:
enabled: true
newrelic-infrastructure:
privileged: true
```
To:
```yaml
newrelic-infrastructure:
enabled: true
privileged: true
```
This behavior is documented here: https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies
As only the first value is evaluated, there is no possibility of doing any type of compatibility layer. That is the reason the legacy value is first for it to be evaluated in case the user changed the value before upgrading.
You cannot test that it does not render. Asserting `hasDocuments.count=0` or using `failedTemplate` in `helm unittest` always return this error:
```
FAIL  Check defaults	tests/newrelic-infrastructure_test.yaml
- newrelic-infrastructure …
```
=> [nri-bundle] Fix bad UX with chart toggles

charts/newrelic-pixie/Chart.yaml, charts/newrelic-pixie/README.md, charts/newrelic-pixie/ci/test-values.yaml, charts/newrelic-pixie/templates/NOTES.txt, charts/newrelic-pixie/templates/configmap.yaml, charts/newrelic-pixie/templates/job.yaml, charts/newrelic-pixie/tests/configmap.yaml, charts/newrelic-pixie/tests/jobs.yaml, charts/newrelic-pixie/values.yaml
No
This PR bumps the Pixie integration to version 2. This version is using a short-running integration that registers the PXL script to run using a New Relic Pixie plugin.
Significant changes:
* The deployment has been replaced by a job
* The ability to add custom scripts was added
=> [newrelic-pixie] Use v2 of the Pixie integration

charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml, charts/nri-bundle/README.md
Bump newrelic-infrastructure to version 3.6.2 that includes namespace filtering.
=> Bump newrelic-infrastructure to version 3.6.2

charts/newrelic-logging/Chart.yaml
No
- Upgrades `newrelic-logging` to use the latest available image tag `1.14.0`, which includes Fluent Bit 1.9.4.
Kubernetes 1.21+ enforces Service Account tokens to be refreshed every hour, as explained [here](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.21).
The `newrelic-logging` DaemonSet is based on the `newrelic/newrelic-fluent-bit-output` image, which in turn is based on the `fluent/fluent-bit` one. We basically run Fluent Bit and we use its `kubernetes` filter [plugin](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes), which basically asks the K8s for pod metadata each time a new pod is launched. This metadata is used to enrich the forwarded logs.
Fluent Bit versions prior to 1.9.4 did not perform the ServiceAccount token …
=> [newrelic-logging] Upgrade to latest image tag version (1.14.0)

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset-windows.yaml
No
Fixes a warning message present in the Windows DaemonSet, due to a leftover of [this previous PR](https://github.com/newrelic/helm-charts/pull/621).
None
Harmless change, just propagating an additional env variable to the Windows containers.
=> [newrelic-logging] Fix missing K8S_BUFFER_SIZE on Windows Helm chart

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/_helpers.tpl, charts/newrelic-logging/templates/clusterrolebinding.yaml, charts/newrelic-logging/templates/daemonset-windows.yaml, charts/newrelic-logging/templates/daemonset.yaml, charts/newrelic-logging/templates/serviceaccount.yaml, charts/newrelic-logging/tests/rbac_test.yaml, charts/newrelic-logging/values.yaml
No.
There is an issue open by GTS saying that not all the charts honor the flag `.global.serviceAccount.create` and `.global.serviceAccount.name`: #875
So at the same time I was reviewing all the charts we maintain, I made also the PR to support the logging chart too.
Enjoy :)
=> [newrelic-logging] Add global service account

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/tests/cl-naming_suffix_test.yaml, library/common-library/Chart.yaml, library/common-library/templates/_naming.tpl, library/common-library/templates/_serviceaccount.tpl
No
It fixes a bug in the common.library's  `truncateToDNSWithSuffix` helper.
- fixes #902 
=> [common-library] fix truncate to dns corner case

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset.yaml
https://github.com/newrelic/helm-charts/issues/81
- Since `hostNetwork` is set to `true`, the env var `HOSTNAME` needs to also
be explicitely set
https://github.com/fluent/fluent-bit/issues/850#issuecomment-536249449
=> [newrelic-logging] DaemonSet - Set HOSTNAME explicitely

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/_helpers.tpl, charts/newrelic-logging/templates/daemonset-windows.yaml, charts/newrelic-logging/templates/daemonset.yaml, charts/newrelic-logging/values.yaml
Problem: [Issue #613][1]. We cannot use `valueFrom` in
`additionalEnvVariables` to add metadata like the pod id as an
environment variable. The code only passes through the `name` and
`value` fields, not `valueFrom`.
Solution: Don't destructure the additionalEnvVariables list at all. Just
emit the whole thing in place.
No.
Allows the use of `valueFrom` in `additionalEnvVars` provided to Fluent Bit containers.
* fixes #613 
=> [newrelic-logging] allow metadata env vars

charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml
Update `newrelic-logging` dependency in `nri-bundle` and bump version
=> [nri-bundle] Update `newrelic-logging` version to `v1.11.5`

.github/renovate.json5, .github/workflows/lint_test_charts.yaml, .github/workflows/release.yml
No.
We need that all the dependencies of the `nri-bundle` have the same version of the `common-library`. For that, the PRs of dependencies of the `nri-bundle` must be grouped in the same PR by renovatebot and we should parse the dependencies for the versions and compare them.
- fixes #883
=> [CI] Test `nri-bundle` integrity

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset-windows.yaml
Windows daemonset is failing due to a typo
=> [newrelic-logging] typo windows

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/README.md, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/README.md, charts/synthetics-job-manager/charts/node-api-runtime/templates/job.yaml, charts/synthetics-job-manager/charts/node-api-runtime/values.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/README.md, charts/synthetics-job-manager/charts/node-browser-runtime/templates/job.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/values.yaml, charts/synthetics-job-manager/values.yaml
No
Adds the ability for customers to configure the `completions` parameter for CronJob types which will mitigate a potential issue where long running jobs may prevent enough jobs from executing each minute. This gives customers the ability to modify this value to suit their particular job workloads.
- Fixes NR-47917
=> [synthetics-job-manager] Allow configuration of `completions` for node-api-runtime and node-browser-runtime jobs

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/README.md, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/values.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/values.yaml, charts/synthetics-job-manager/values.yaml
NO
Adds resource request and limits to runtimes. This is a bug ticket that was reported by ANZ: [NR-46521](https://issues.newrelic.com/browse/NR-46521).
**Promise these numbers didn't come out of thin air!!!! These are actually the old minion request / limit configs based on job type. I used them as a jumping off point and didn't need to increase them because they are working.**
Node Runtime: 
API Runtime: 
Proof of concept: 
These two are run on the eks cluster with the new resource limits and request I implemented in this PR and it shows that the values defined here will pass checks without any problem.
Monitor 1 (Scripted Browser Monitor) : https://staging.onenr.io/0PoR87rG6wG
Monitor 2 (Scripted API Monitor): https://staging.onenr.io/09MR2NvX2RY
*(optional, in `fixes #<issue number>(, …
=> [synthetics-job-manager]: Adding resource limits and request for runtimes

charts/synthetics-minion/Chart.yaml, charts/synthetics-minion/templates/statefulset.yaml
This is fixing the env variable PRIVATE_LOCATION_KEY -> MINION_PRIVATE_LOCATION_KEY
=> [synthetics-minion] Fix environment variable private location key name

.github/workflows/security.yaml
No.
We are adding security scanning to every PR to try to reduce the number of vulnerabilities we release.
- fixes #965
=> [all-charts] Add security pipeline (NEWRELIC-4232)

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset-windows.yaml
No
Fixes the windows fluent-bit daemonset variable.
Windows daemonset should include the $ in front of the variable unlike linux one because we're iterating over windows versions.
=> [newrelic-logging] Use the correct variable for retry limit in windows

.github/ct-install.yaml, .github/ct-lint.yaml, .github/workflows/lint_test_charts.yaml, .github/workflows/release.yml, charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml, charts/nri-bundle/README.md, charts/nri-bundle/README.md.gotmpl, charts/nri-bundle/values.yaml
Yes!
This enables the possibility to install New Relic's Prometheus Configurator using the `nri-bundle`.
=> [nri-bundle] Add the public preview of the Prometheus Configurator (NR-55440)

README.md, charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml, charts/nri-bundle/README.md, charts/nri-bundle/values.yaml
No.
Fixes the toogle of the new Prometheus agent to honor the false that is in the `values.yaml`
=> [nri-bundle] Fix agent toogle and READMEs

charts/newrelic-logging/Chart.yaml
No
Version of the `newrelic-logging` was not porperly bumped and is blocking the release CI.
=> [newrelic-logging] Bump logging chart version properly

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No 
Updates the ping-runtime version of our helm-chart
- Resolves the vulnerability detailed in https://nvd.nist.gov/vuln/detail/CVE-2022-42889
=> [synthetics-job-manager] Update ping runtime version 1.9.0

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/templates/job.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/templates/job.yaml
No
Fixed an indentation error in the subcharts for the New Relic Synthetics Job Manager 
- fixes #986
None
- [X ]Chart Version bumped
- [X ] Title of the PR starts with chart name (e.g. `[mychartname]`)
=> [synthetics-job-manager] Fix label indents for CronJobs

charts/nri-bundle/Chart.yaml, charts/nri-bundle/values.yaml
This PR fixes an issue while upgrading the `nri-bundle` with KSM v2.
For more details, check this [issue](https://github.com/prometheus-community/helm-charts/issues/568).
=> Add KMS upgrade path workaround

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
No
Updates the release version of the node-api-runtime image
- Adds node-vault and otp auth modules
=> [synthetics-job-manager] Updating node-api-runtime chart with v1.1.29

.github/CODEOWNERS
No
Deletes the new CODEOWNERS file located at .github/CODEOWNERS which appears to be conflicting with existing CODEOWNERS file at root, causing the k8s011y group to be required as an approver for charts owned by synthetics. If this was intentional & we DO want k8s011y to additionally review charts owned by other teams then please disregard!
N/A
I think there's only supposed to be one CODEOWNERS file per branch - could be wrong though. 
=> delete extra codeowners file

charts/newrelic-pixie/Chart.yaml, charts/newrelic-pixie/templates/_helpers.tpl, charts/newrelic-pixie/values.yaml
No
This PR makes `newrelic-pixie` chart's handling of `lowDataMode` same as other charts to allow setting it by either `global.lowDataMode` or `newrelic-pixie.lowDataMode`.
Specifically, it adopts [_low-data-mode.tpl](https://github.com/newrelic/helm-charts/blob/af747af93fb5b912374196adc59b552965b6e133/library/common-library/templates/_low-data-mode.tpl) from the `common-library` chart.
Longer term, we should look into moving this chart to use the `common-library` chart instead of re-defining helpers.
None
Hi please review this thank you.
=> [newrelic-pixie] Use standard pattern for lowDataMode to suport local overrride

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml, charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No.
Updating the chart and app versions in the synthetics-job-manager chart after a deploy. 
- fixes #
=> [synthetics-job-manager]: Updating helm charts after deploy

library/CHART-TEMPLATE/templates/job.yaml
No
We are working on updating the Kubernetes registry references:
k8s.gcr.io image registry will be redirected to registry.k8s.io on Monday March 20th.
All images available in k8s.gcr.io are available at registry.k8s.io.
See https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
=> Fix reference to outdated Kubernetes repo

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/templates/_helpers.tpl, charts/synthetics-job-manager/templates/deployment.yaml
No
- Pulls in the latest version of Synthetics Job Manager
- Sets the HEAVYWEIGHT_WORKERS env variable to the sum of parallelism for the runtimes
NR-99199
🐱 🌵 🍰 
=> [synthetics-job-manager] set heavyweight workers based on parallelism settings NR-99199

charts/nri-bundle/Chart.yaml
No
A recent change to the nri-bundle Chart (https://github.com/newrelic/helm-charts/pull/1061) did not trigger dependency version updates from the renovate bot, so the nri-bundle version stayed at 5.0.8. The release workflow seems to have recognized this as a change and is trying to generate a new nri-bundle, but fails because the bundle for 5.0.8 already exists. Subsequent PR merges fail, presumably because the change is still detected. This change manually updates the nri-bundle chart version in order to let the release workflow package up the nri-bundle properly.
Slack discussion for internal NR for more context: https://newrelic.slack.com/archives/C2XN6HL2G/p1681249969204639
=> [nri-bundle] manually update nri-bundle chart version

charts/synthetics-job-manager/Chart.yaml
No
The latest release of SJM required a rollback. It's unlikely customers running private SJMs will be very affected by the bug but better safe.
=> [synthetics-job-manager] release rolled back sjm

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml, charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No
Updates the helm charts to use the latest release versions of the Synthetics Job Manager and its associated runtimes:
Synthetics Job Manager: `release-246`
synthetics-ping-runtime: `1.19.0`
synthetics-node-browser-runtime: `1.1.115`
synthetics-node-api-runtime: `1.1.40`
=> [synthetics-job-manager] update job manager and runtime chart versions

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/README.md, charts/newrelic-logging/k8s/README.md, charts/newrelic-logging/values.yaml
No
This PR:
- Deprecates the contents of the "k8s" folder. This folder contained some hand-made K8s manifests that have become obsolete over time. Users wishing to install the New Relic Logs Kubernetes plugin can now do so by using our [Kubernetes integration Guided Install](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/) instead.
- Simplifies and adapts the README.md file by removing some irrelevant stuff, adapting the proxy section to use Helm-based configuration values and referencing our official docs with regards to how to install/uninstall the Helm chart.
=> [newrelic-logging] Deprecate old "k8s" folder, simplify and adapt README.md

charts/newrelic-logging/Chart.yaml
Upgrade the logging helm chart to use the last version of Fluent Bit output plugin
* Upgraded logging helm chart to v1.16.0.
* Upgraded app version to v1.17.3
=> [newrelic-logging] Upgrade helm chart to v1.16.0 and app version to v1.17.3

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/values.yaml
Defining multiple parsers is only supported for multiline parsers. Furthermore, we can now leverage the [built-in multiline parsers for `cri,docker`](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-and-containers-v1.8).
=> [newrelic-logging] Leverage built-in `multiline.parser`s

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset-windows.yaml, charts/newrelic-logging/tests/images_test.yaml
No
In [this PR](https://github.com/newrelic/helm-charts/pull/1126/files#diff-c0bb284370f360ccbc2828f1011058c92df6170d86b07fb4a911d4a93a356375R57) we accidentally broke the `newrelic-logging` chart for Windows -- our Fluent Bit Windows image has a suffix containing the OS name.
NR-146879
=> [newrelic-logging]: Add back image tag suffix for Windows for newrelic-logging

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
* Updates the helm chart for node browser runtime, api runtime, and synthetics job manager to use latest runtime releases
* 
=> [synthetics-job-manager] node browser and api runtimes deploy

.github/workflows/post-release.yml, charts/nri-bundle/Chart.yaml
=> fix: Add `--repo` flag to open PR in newrelic repo

.github/renovate.json5, .github/workflows/test-renovate-configuration.yaml
No
I merged an invalid configuration for renovatebot on the PR #1155
This PR should add a test to not allow to merging an invalid configuration and fix the configuration.
- fixes #1180
The first commit (or set of commits) tries to create a pipeline that fails because the configuration is broken at the time of opening this PR.
After having a failing pipeline, I'll add a commit that fixes the config.
I advise the reviewer to go commit by commit. I'll try to squash them to make the review easier :)
=> [chore] Add a ci pipeline to test renovate's configuration on PR

.github/workflows/release.yml
See this [release](https://github.com/newrelic/helm-charts/actions/runs/6655400256/job/18085596673) failing.
=> Add missing flux2 helm repository

charts/super-agent-deployment/Chart.yaml, charts/super-agent-deployment/templates/_helpers.tpl, charts/super-agent-deployment/templates/deployment-superagent.yaml, charts/super-agent-deployment/templates/rbac.yaml, charts/super-agent-deployment/tests/rbac_test.yaml, charts/super-agent-deployment/tests/securityContext_test.yaml
Changes:
- After the changes introduced by @rubenruizdegauna the container needs to be able to write to /var/lib. For now an empty dir is enough
- The SA needs to be able to CRUD configmaps
- Reduced the scope of the clusterRole to a single namespace
=> fix(cm): add config maps and make superAgent compatible

charts/super-agent-deployment/Chart.yaml, charts/super-agent-deployment/ci/test-values.yaml, charts/super-agent-deployment/templates/_helpers.tpl, charts/super-agent-deployment/tests/configmap_config_test.yaml
Following up the support of k8s values in the super-agent [newrelic-super-agent#283](https://github.com/newrelic/newrelic-super-agent/pull/283), this PR includes the cluster_name
and the namespace in the super-agent config map. 
❗ The pipeline will fail since we are using the `nightly` version of the super-agent and it already expects these new values. Consequently, the previous version of the chart doesn't work anymore.
=> [super-agent-deployment] include cluster_name and namespace in the config-map

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset-windows.yaml, charts/newrelic-logging/templates/daemonset.yaml, charts/newrelic-logging/templates/podsecuritypolicy.yaml
No
We think that `hostNetwork: true` got copied-and-pasted from another chart when the `newrelic-logging` was originally created a few years ago. We want the `newrelic-logging` pod to have as little access as possible, to increase security -- it should just need as much access as it needs to do its job and no more. As far as we can tell, it doesn't need to connect to the host network.
Also, PodSecurityPolicy is now deprecated and
[removed from the latest versions](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) of Kubernetes, but we're keeping it because we have customers are older versions of Kubernetes. There is no direct replacement for a PSP, see [here](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-fut …
=> [newrelic-logging]: Remove unneeded hostNetwork setting

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/tests/images_test.yaml
Upgrade the logging helm chart to use the last version of Fluent Bit output plugin
* Upgraded logging helm chart to v1.19.0.
* Upgraded app version to v1.19.0
=> [newrelic-logging]  Upgrade helm chart to v1.19.0 and app version to v1.19.0

charts/super-agent-deployment/Chart.yaml, charts/super-agent-deployment/templates/deployment-superagent.yaml, charts/super-agent-deployment/tests/securityContext_test.yaml
No
This allows the super-agent to redeploy when configuration changes.
=> [super-agent-deployment] Redeploy super-agent on configmap changes (NR-182327)

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
Nope :) 
Updates node-api-runtime chart to pull latest version
- fixes #
=> [synthetics-job-manager] update helm chart to reflect latest node api runtime deploy

.github/renovate.json5
Given the fact that this repository is shared by various teams with different rules on when to merge dependencies, it is not feasible to allow automerge without the risk of unintended merges happening in the future. This PR completely disables automerge for Renovate, forcing Renovate to create PRs that need to be manually merged by developers.
=> fix: Update Renovate config file

charts/super-agent/Chart.lock, charts/super-agent/Chart.yaml
This reverts commit 594230530073f1ac622a727040230560a3d3f9a8.
=> Revert "chore(deps): update helm release flux2 to v2.12.2 (#1222)"

.github/workflows/release.yml
Last week, [this workflow run](https://github.com/newrelic/helm-charts/actions/runs/7710787642/job/21014874442) created tag `nri-bundle-5.0.61` after tag `super-agent-0.0.2-beta`, so we know for sure temporal dependencies between the two tags.
However, this week [this workflow run failed](https://github.com/newrelic/helm-charts/actions/runs/7799298965/job/21269820082) because it read tag `super-agent-0.0.2-beta` as if it were the latest.
While it is not clear the source of the issue (bad cache, chart releaser action bug?), we can use the flag `--skip-existing` to tell the chart releaser not to fail when a release already exists, adding more reliability to our workflow.
=> fix: Skip releasing chart if it already exists

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No
Adds latest ping runtime release
- fixes #
=> [synthetics-job-manager] Add ping runtime release to helm chart

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset.yaml
When setting `extraVolumeMounts` and `exposedPorts`
=> [newrelic-logging] fix: Using extraVolumeMounts and exposedPorts generates invalid YAML

charts/super-agent-deployment/Chart.yaml, charts/super-agent-deployment/README.md, charts/super-agent-deployment/templates/uninstall-job.yaml, charts/super-agent-deployment/values.yaml
No
This PR includes a helm pre-delete hook to delete that are managed by the super-agent, since some of the resources may not be garbage collected.
There are still _race conditions_ when this chart is deployed by flux and flux is uninstalled in the same step (the CRs can be deleted after flux is uninstalled and the underlying kubernetes resources stop being managed). This will be addressed in a follow-up PR by updating the uninstall-job in the `super-agent` chart (#1279).
=> [super-agent-deployment] include uninstall job

charts/super-agent/Chart.yaml, charts/super-agent/templates/install-job.yaml
This PR improves the Kubernetes Job script by better distinguishing between actual errors and warnings in kubectl apply output. 
It checks the command's exit status and looks for success indicators, ensuring only failures trigger error messages. This change should clarify a bit the feedback on CRs application.
=> Improve super-agent helm chart error handling

charts/super-agent-deployment/Chart.yaml, charts/super-agent-deployment/README.md, charts/super-agent-deployment/templates/uninstall-job.yaml
no
The `super-agent-deployment` uninstall-job name was conflicting with the `super-agent` uninstall job name, therefore when `super-agent-deployment` is installed through `super-agent` via Flux, the uninstall was not behaving as expected.
=> [super-agent-deployment] fix conflicting names for uninstall job

charts/super-agent/Chart.yaml, charts/super-agent/README.md, charts/super-agent/templates/_helm-release.yaml, charts/super-agent/templates/uninstall-job.yaml, charts/super-agent/values.yaml
No
~Extends the `super-agent` chart helm delete hook to remove the CRs managed by the super-agent. This is needed because there is a _race condition_ when uninstalling the chart. The CRs might be deleted after Flux is uninstalled, consequently, the underlying resources are keep in the cluster. Since the pre-delete hook is executed before uninstalling the chart, this we we assure the CR deletion is handled by Flux.~
Since the resources managed by the super-agent are deleted during the `super-agent-deployment` uninstallation, in order to guarantee those are properly deleted here, we need to assure that the corresponding job is executed before Flux is uninstalled. The [default uninstall configuration](https://fluxcd.io/flux/components/helm/helmreleases/#uninstall-configuration) for Flux …
=> [super-agent] remove super-agent crs on uninstall

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/tests/images_test.yaml
No
It bumps the image for newrelic-logging integration, it uses the plugin version 1.19.2 that user fluent-bit 2.2.2 for docker images. https://github.com/newrelic/newrelic-fluent-bit-output/pull/150
It fixes following vulnerabilities added by libpq5
**HIGH**
[CVE-2023-39417](https://avd.aquasec.com/nvd/cve-2023-39417): postgresql: extension script @substitutions@ within quoting allow SQL injection
[CVE-2023-5869](https://avd.aquasec.com/nvd/cve-2023-5869): postgresql: Buffer overrun from integer overflow in array modification
**MEDIUM**
[CVE-2023-5868](https://avd.aquasec.com/nvd/cve-2023-5868): postgresql: Memory disclosure in aggregate function calls
[CVE-2023-5870](https://avd.aquasec.com/nvd/cve-2023-5870): postgresql: Role pg_signal_backend can signal certain superuser processes. …
=> [newrelic-logging] Bump newrelic-fluentbit-output image to 1.19.2

charts/synthetics-minion/Chart.yaml
- No
- Updates the synthetics-minion helm chart to use the latest containerized private minion release version v3.1.6
- Removes warning messages related to the Blackbird module
=> [synthetics-minion] Update synthetics-minion helm chart v3.1.6

charts/newrelic-pixie/Chart.yaml, charts/newrelic-pixie/templates/job.yaml
We add a "TTL" or time-to-live for the container init Job in `newrelic-pixie`. This fixes a bug where users that wanted to upgrade the helm chart could not because the Job was immutable. After adding the TTL, the Job is removed from the cluster.
=> [newrelic-pixie] Add ttl limit for container init Job in.

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/values.yaml
No
It reverts to using the previous matching for logs, so that all logs are sent by the NR plugin. Otherwise, if somebody defined an additional input via `fluentBit.config.extraInputs`, they would get ignored.
None
=> [newrelic-logging] Revert to previous routing

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/values.yaml
No
Adds source dimension to metrics to indicate that they come from a Kubernetes cluster. This will allow us, later on, to distinguish metrics coming from other kind of deployments (infra-agent, etc.)
None
=> [newrelic-logging] Add metric source

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/README.md, charts/synthetics-job-manager/values.yaml
No
Fixes helm chart for SJM so users are able to mount volumes. Previously, when using a values file outside of the helm chart, the merge to the values file within the chart would break because `persistence` and `customNodeModules` were not being recognized as maps. 
=> [synthetics-job-manager] fix volume mount for SJM

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
No
Brings SJM image and runtime images up to date with what is available in DockerHub
=> [synthetics job manager] bring sjm and node-api-runtime up to date

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/values.yaml
No
Adds double quotes to the attribute cluster_name key value pairs in the values.yaml file. This will allow the cluster name containing spaces.
- This will fix the error **invalid record parameters, expects ‘KEY VALUE’**
=> [newrelic-logging] fix: Fix key value pair error for the cluster name containing space

charts/super-agent-deployment/Chart.yaml, charts/super-agent-deployment/README.md, charts/super-agent-deployment/values.yaml
Just giving an example to enable and query the status server:
```json
{
"super_agent": {
"healthy": true
},
"opamp": {
"enabled": true,
"endpoint": "https://opamp.service.newrelic.com/v1/opamp",
"reachable": true
},
"sub_agents": {
"open-telemetry": {
"agent_id": "open-telemetry",
"agent_type": "newrelic/io.opentelemetry.collector:0.1.1",
"healthy": true
}
}
}
```
=> [super-agent-deployment] provide example for status server

.github/renovate.json5
No
My mail is being flooded by flux upgrades because the PR of the upgrade is not being merged.
We do not want to merge it (yet) and we will upgrade flux if it is needed. If we remove the PR from renovate we remove also the possibility of merging it by mistake.
=> [super-agent] Disable flux on renovatebot

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/tests/images_test.yaml
It bumps the image for newrelic-logging integration, it uses the plugin version 2.0.0 that user fluent-bit 3.0.4 for docker images. https://github.com/newrelic/newrelic-fluent-bit-output/pull/154
it fixes critical vulnerability https://nvd.nist.gov/vuln/detail/CVE-2024-4323 
=> [newrelic-logging] Bump newrelic-fluentbit-output image to 2.0.0

.github/workflows/lint_test_charts.yaml, charts/super-agent/Chart.yaml, charts/super-agent/values.yaml
no 
just fixes some typos 
- fixes #
don't think this requires a chart version to be bumped but I can if needed
=> [super-agent] typo fixes so codespell stops yelling

library/CHART-TEMPLATE/Chart.lock, library/CHART-TEMPLATE/Chart.yaml, library/CHART-TEMPLATE/README.md, library/CHART-TEMPLATE/templates/example-cm-insightskey.yaml, library/CHART-TEMPLATE/templates/example-insights-secret.yaml, library/CHART-TEMPLATE/templates/example-license-secret.yaml, library/CHART-TEMPLATE/templates/example-secret.yaml, library/CHART-TEMPLATE/templates/integration-deployment.yaml, library/CHART-TEMPLATE/templates/sidecar-deployment.yaml, library/CHART-TEMPLATE/tests/cl-agent_config_test.yaml, library/CHART-TEMPLATE/tests/cl-images_pull_secrets_test.yaml, library/CHART-TEMPLATE/tests/cl-images_security_context_container_test.yaml, library/CHART-TEMPLATE/tests/cl-images_security_context_pod_test.yaml, library/CHART-TEMPLATE/tests/cl-insights_helpers_test.yaml, library/CHART-TEMPLATE/tests/cl-insights_secret_test.yaml, library/CHART-TEMPLATE/tests/cl-priority_class_name_test.yaml, library/CHART-TEMPLATE/values.yaml, library/common-library/Chart.yaml, library/common-library/DEVELOPERS.md, library/common-library/templates/_insights.tpl, library/common-library/templates/_insights_secret.yaml.tpl, library/common-library/templates/_license.tpl
No.
Issue #1324 ask for support to have the insights key out of the `values.yaml`. This is an opportunity to have the same UX for that key that we have for the rest of secrets/licenses.
This PR does not fix any issue yet but it is the first step to fix #1324.
Once this PR is merged, we have the tooling to add `common-library` to `nri-statsd`.
Some test were not passing because of updates of `helm unittest` so I have to fix them.
=> [common-library] Add insights key helpers

.github/workflows/lint_test_charts.yaml, charts/super-agent/Chart.lock, charts/super-agent/Chart.yaml, charts/super-agent/charts/super-agent-deployment/Chart.yaml, charts/super-agent/charts/super-agent-deployment/templates/rbac.yaml, charts/super-agent/charts/super-agent-deployment/templates/uninstall-job.yaml
This PR:
-  forces `CT` to use a separate naspace so that we are sure `kubectl delete ns ...` will wait that resources are garbage collected (`ct` is not doing so when running helm delete)
- modifies the uninstall job to make sure the super agent is NOT running before deleting resources. This is needed to avoid the SA recreating it right after  
=> [super-agent] Making sure all resources are deleted

charts/super-agent/Chart.lock, charts/super-agent/Chart.yaml, charts/super-agent/charts/super-agent-deployment/Chart.yaml, charts/super-agent/charts/super-agent-deployment/templates/_helpers.tpl, charts/super-agent/charts/super-agent-deployment/templates/deployment-superagent.yaml, charts/super-agent/charts/super-agent-deployment/templates/secret.yaml, charts/super-agent/charts/super-agent-deployment/tests/configmap_fleet_configs_test.yaml, charts/super-agent/charts/super-agent-deployment/tests/deployment_superagent_env_test.yaml, charts/super-agent/charts/super-agent-deployment/tests/licenseKey_test.yaml, charts/super-agent/ci/test-values.yaml, charts/super-agent/tests/placeholder, charts/super-agent/values.yaml
- Adds license key as env variable  from the secret for the SA deployment. This will allow to use env vars placeholders in configs rather than plain secrets for sub-agents.
- fixes #
=> [super-agent] feat: add license key as env from secret (NR-293501)

charts/super-agent/Chart.lock, charts/super-agent/Chart.yaml, charts/super-agent/charts/super-agent-deployment/Chart.yaml, charts/super-agent/charts/super-agent-deployment/templates/deployment-superagent.yaml, charts/super-agent/charts/super-agent-deployment/tests/deployment_superagent_env_test.yaml, charts/super-agent/ci/test-values.yaml, charts/super-agent/values.yaml
no
- Leveraging env_var for cluster instead of fixed value
- Improving test structure
=> [super-agent] Leverage env var for cluster name

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml, charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No.
Updates the synthetics node-api and node-browser runtime versions to the latest releases
- fixes CVEs related to the ubuntu version and node package dependencies in both runtimes
=> [synthetics-job-manager] update runtimes (node-api v1.2.86 and node browser v.2.3.69)

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/tests/images_test.yaml
No.
This PR bumps the image for newrelic-logging integration, it uses the plugin version 2.0.2 that user fluent-bit 3.1.2 for docker images. Related PR: https://github.com/newrelic/newrelic-fluent-bit-output/pull/166 
- fixes #NR-310459
This fixes trivy ticket of the image [cf-registry.nr-ops.net/maas/docker-atlantis-fluent-bit](http://cf-registry.nr-ops.net/maas/docker-atlantis-fluent-bit). 
1. Unit test: helm unittest charts/newrelic-logging
2. Installation successful: `helm upgrade --install newrelic-bundle --set licenseKey=key /Users/mjha/work/helm-charts/charts/newrelic-logging -n newrelic`
[Place an '[x]' (no spaces) in all applicable fields. Please remove …
=> [newrelic-logging] Bump newrelic-fluentbit-output image to 2.0.2

charts/nr-k8s-otel-collector/Chart.yaml, charts/nr-k8s-otel-collector/README.md, charts/nr-k8s-otel-collector/templates/daemonset.yaml, charts/nr-k8s-otel-collector/templates/deployment.yaml, charts/nr-k8s-otel-collector/tests/env_vars_from_test.yaml, charts/nr-k8s-otel-collector/tests/env_vars_test.yaml, charts/nr-k8s-otel-collector/values.yaml
No. This is a modification to 'nr-otel-for-k8s', which is currently maintained by @csongnr and @dbudziwojskiNR 
This PR exposes the option to add additional pod EVs to the deployment and daemonset running on kubernetes. I ran into a use case where I needed to be able to customize the 'nr-otel-for-k8s' service with a custom collector config, but once I did so I was unable to securely pass values to that config. In order to securely pass values to a custom config, having access from the values file to provide additional EVs is helpful.
=> [nr-k8s-otel-collector] - exposing pod EVs to configuration in values file

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
no
Updates the synthetics-job-manager chart version to use the latest release of the synthetics-ping-runtime
- fixes a permission issue when running the synthetics-ping-runtime as a non-root user
=> [synthetics-job-manager] update ping-runtime version (1.47.0) and chart version

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/daemonset.yaml
No
When using `persistentVolume` mode, the env variable `FB_DB` references `NODE_NAME`. This reference is currently not resolved, because `NODE_NAME` is defined after `FB_DB`. Therefore, only a single database file named `'$(NODE_NAME)-fb.db'` is created in the persistent volume, instead of one file for each node. #1408 traced the problem down to this [change](https://github.com/newrelic/helm-charts/commit/f6c71610196899e6248fb0b641ace0be4d6c3df9#diff-dba7a505c5df68aac95df70ba65d1a43ac0349a7692e6a1ecd2899854ba90894L108-L128), which moved the definition of `NODE_NAME` after the definition of `FB_DB`.
This PR fixes this, by moving the definition of `NODE_NAME` before the definition of `FB_DB` again.
The behavior of kubernetes for dependent environment variables is documented …
=> [newrelic-logging] Adjust order of env list in daemonset to fix dependency reference

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/tests/images_test.yaml
Is this a new chart
No.
What this PR does / why we need it:
This PR bumps the image for newrelic-logging integration, it uses the plugin version 2.1.0 that user fluent-bit 3.1.9 for docker images. Related PR: https://github.com/newrelic/newrelic-fluent-bit-output/pull/168
Which issue this PR fixes
(optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged)
fixes #[NR-311475](fixes : https://new-relic.atlassian.net/browse/NR-311475)
This fixes trivy ticket of the image [cf-registry.nr-ops.net/maas/docker-atlantis-fluent-bit](http://cf-registry.nr-ops.net/maas/docker-atlantis-fluent-bit).
Testing done.
Unit test: helm unittest charts/newrelic-logging
Installation successful: helm upgrade --install newrelic-bundle --set licenseKey=key …
=> Bump newrelic-fluentbit-output image to 2.1.0

charts/newrelic-logging/Chart.lock, charts/newrelic-logging/Chart.yaml
For newrelic-logging, updates the common-library from 1.2.0 to 1.3.0.  The Pull Request check `Test nri-bundle dependencies has the same version of the common-library` currently fails due to the mis-matched common library dependency.  That was failing all the PRs for updating helm chart dependencies.
- fixes #
=> [newrelic-logging] update common library version to unblock tests

charts/nr-ebpf-agent/Chart.lock, charts/nr-ebpf-agent/Chart.yaml, charts/nr-ebpf-agent/templates/_helpers.tpl, charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml, charts/nr-ebpf-agent/templates/secrets.yaml
No.
This chart adds support for some environment variables/secrets that are documented in the NRI-bundle. 
This removes the need for the user to supply separate secrets specifically for the eBPF agent. 
This change will allow for a more seamless install for the customers who choose to install the eBPF agent as part of the nri bundle. (When the eBPF agent is added to the bundle.)
- fixes # N/A
Support for global ingest keys is documented in the nri-bundle/read.me. 
If users are installing this chart by itself, they should use the values.licenseKey not global vars supplied by the bundle.
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated …
=> [nr-ebpf-agent] Support nri-bundle supplied secrets. 

charts/nr-ebpf-agent/Chart.yaml, charts/nr-ebpf-agent/templates/_helpers.tpl, charts/nr-ebpf-agent/templates/otel-collector-config.yaml
No. 
Adds support for values.global.chart as the chart name for the ebpf agent. 
Is needed to support the ebpf agent being added to the nri bundle. 
- fixes # N/A
values.global.chart is coming from the nri bundle values.yaml and is documented in the nri-bundle readme. 
=> [nr-ebpf-agent] Supporting global.cluster name supplied by the nri bundle.

CODEOWNERS, charts/super-agent/Chart.lock, charts/super-agent/Chart.yaml, charts/super-agent/README.md, charts/super-agent/charts/super-agent-deployment/Chart.yaml, charts/super-agent/charts/super-agent-deployment/templates/deployment-superagent.yaml, charts/super-agent/charts/super-agent-deployment/tests/auth_secret_test.yaml, charts/super-agent/charts/super-agent-deployment/tests/deployment_superagent_subagent_configs_test.yaml
no
follow up of https://github.com/newrelic/helm-charts/pull/1482
In the past there was a similar PR and @gsanchezgavier suggested to use extra volumes. I needed to modify how we mount the agent Control configMap to allow such approach
- [] Variables are documented in the README.md -> Expected not to be exposed
=> feat(dev): add option for dynamicAgent

CODEOWNERS, charts/synthetics-job-manager/Chart.yaml
no
adds some current synthetics engineers to sjm chart maintainers list
=> [synthetics-job-manager] chore: add engineers to sjm chart maintainers

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/README.md, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/_helpers.tpl, charts/agent-control/charts/agent-control-deployment/tests/configmap_agentcontrol_config_test.yaml, charts/agent-control/values.yaml
no
with this PR we point to the latest release available of the agent control and we introduce a new `value` for the fleet_id
=> [agent-control] fleet_id has now a specific value

charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/tests/auth_secret_test.yaml, charts/agent-control/charts/agent-control-deployment/tests/deployment_agentcontrol_env_test.yaml, charts/agent-control/charts/agent-control-deployment/tests/deployment_agentcontrol_subagent_configs_test.yaml, charts/agent-control/charts/agent-control-deployment/tests/preinstall_job_test.yaml, charts/agent-control/values.yaml
no
After we moved to a sub-chart approach naming got compromised, now we have something like:
```
agent-control-agent-control-deployment-6b9496bcb9-g5ncj
agent-control-agent-control-deployment
```
In particular we have a repetition and a -deployment suffix
After this PR, we are aligning the two chartName so that we forget about the `-deployment` suffix and the suplication
```
agent-control-86d6dd7ddf-r64lm
agent-control
```
=> [agent-control] improve naming

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/_helpers.tpl, charts/agent-control/charts/agent-control-deployment/tests/configmap_agentcontrol_config_test.yaml, charts/agent-control/values.yaml
No
This PRs includes the chart version in the Agent Control configuration so it can be reported.
=> [agent-control]: add chart version to agent-control config [NR-348101]

charts/agent-control/Chart.yaml, charts/agent-control/README.md, charts/agent-control/charts/agent-control-deployment/templates/_helpers.tpl, charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml, charts/agent-control/charts/agent-control-deployment/tests/preinstall_job_test.yaml, charts/agent-control/values.yaml
no
removing the L1 info from the values name
=> [agent-control] Rename L1 values

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/deployment-agentcontrol.yaml, charts/agent-control/charts/agent-control-deployment/tests/deployment_agentcontrol_env_test.yaml
no
Includes additional env-vars in agent-control deployment to allow a centralized configuration of common values.
- fixes #
=> [agent-control]: add additional env-vars to make subagents config easier

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
This PR sets a backoffLimit for the agent-control installation job lower than the default in order to improve troubleshooting.
=> [agent-control] set backoffLimit to pre-install job

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/README.md, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml, charts/agent-control/charts/agent-control-deployment/tests/preinstall_job_test.yaml, charts/agent-control/values.yaml
Uses a dedicated image for the system identity registration step for Agent Control deployments.
https://new-relic.atlassian.net/browse/NR-362687
=> [agent-control] build: use specific system identity registration image

charts/nri-bundle/Chart.lock, charts/nri-bundle/Chart.yaml
No. 
It bumps the version of the eBPF agent. 
Fixes a bug where helm installs that are not named "nr-ebpf-agent" brick the eBPF Agent. 
- fixes #
=> [NRI-Bundle] Bumping eBPF Agent.

charts/nr-ebpf-agent/Chart.yaml, charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml
No. 
Stops us from using the config option `hostNetwork: true` for the otel collector.
This config binds the otel collector's network to the network of the host. 
One byproduct of this is that the port's uses are the same ports of the host. 
By default this is not the case. Ports on a container can bind to any open port on the host. 
However with this option it binds strictly to the same host port. 
This causes an issue if other containers on the node are trying to bind the the same port. 
This is known as a "port conflict" and will only allow one container to bind to the port, leaving the other container in a bad state. 
By decoupling the collector's networking from the host, our otel collector can choose any free port instead of being bound to a specific one. This reduces the likelihood …
=> [nr-ebpf-agent] Stop using host network for Otel Collector

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/_helpers.tpl, charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
This PR updates the L2 identity creation endpoints and query
~We'll keep it as a draft until the whole flow is validated~ (done)
=> [agent-control] update system identity creation query

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml, charts/agent-control/charts/agent-control-deployment/templates/uninstall-job.yaml
- Agent-control : Added backofflimit and ignore-not-found to the uninstall-job
=> [agent-control] fix: Added backofflimit and ignore-not-found to the uninstall-job

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/tests/images_test.yaml
This PR upgrades to the newly released fluent bit output image
- fixes #
This doesn't fix any issue
=> [newrelic-logging] Bump fluent-bit-output image to 2.2.0

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/deployment-agentcontrol.yaml, charts/agent-control/charts/agent-control-deployment/tests/deployment_agentcontrol_env_test.yaml
This PR removes the environment variable used to set up the license-key header in OpAMP communication
=> [agent-control]: remove opamp license-key header [NR-361577]

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/templates/_helpers.tpl, charts/newrelic-logging/tests/fluentbit_monitoring_config_test.yaml, charts/newrelic-logging/values.yaml
This Pull Request addresses a bug where the cluster name was not included in the values file, resulting in an inability to append an empty cluster name when adding labels. This fix ensures that an empty cluster name is appended by default, thereby allowing labels to be correctly appended in the Prometheus scraper configuration.
Details
Issue: The absence of a cluster name in the values file prevented the addition of an empty value for the cluster name during the label configuration in Prometheus scrapers.
Fix: The values file has been updated to include an empty cluster name by default. This update facilitates the proper addition of labels, even when no specific cluster name is provided.
Impact: Ensures that Prometheus scrapers can append labels successfully, thereby maintaining …
=> fix: fixed test cases and empty cluster name

charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml, charts/agent-control/charts/agent-control-deployment/Chart.yaml, charts/agent-control/charts/agent-control-deployment/templates/rbac.yaml
no
drops a permission that is not needed anymore
This is blocked till [this](https://github.com/newrelic/newrelic-agent-control/pull/1086) is merged and released 
=> [agent-control] drop unused permission

charts/newrelic-logging/Chart.yaml, charts/newrelic-logging/tests/images_test.yaml
No
This PR updates the appVersion and chart version of the logging chart
* Attempts to bump up underlying fluent bit version to 3.2.7 to address these critical CVEs: https://fluentbit.io/announcements/v3.2.7/#:~:text=OpenTelemetry%20input%3A,CVE%2D2024%2D50608
=> [newrelic-logging] bump up appVersion and chart version of logging chart

.github/workflows/lint_test_charts.yaml, charts/agent-control/Chart.lock, charts/agent-control/Chart.yaml
We are bumping the flux version used by the agent-control to the latest version to allow adding the attribute disableTakeOwnership.
=> [agent-control] chore(deps): update helm release flux2 to 2.15.0

charts/synthetics-job-manager/Chart.yaml, charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
=> node-api-runtime latest release

charts/agent-control-deployment/Chart.yaml, charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml, charts/agent-control-deployment/templates/uninstall-job.yaml
no
Changes the secret ownership so that it gets deleted by the agent-control-cli
Adding the agent-id to specify which component is leveraging leveraging the secret and to avoid the garbage collector to complain
=> [agent-control-deployment] secret ownership

charts/nr-k8s-otel-collector/Chart.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrole.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrolebinding.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset-configmap.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment-configmap.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/secret.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/service.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/serviceaccount.yaml, charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml, charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
1. Fixes a typo for the openshift inside processors.
2. Removes the attributes/self because it is not needed anymore.
3. Uses k8sattribute processor which is being used inside deployment configmap
4. Factors the prometheus into a new pipeline
- fixes #
=> [nr-k8s-otel-collector] Apply groupbyattr and transform ksm with correct k8sattributes in daemonset

charts/agent-control-deployment/Chart.yaml, charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
no
Improves the security of the container used in the preinstallation job.
Moves the folder where the private key is stored inside `/tmp`. That will relax privileges constraints. We won't need to use `root` user anymore to create the folder.
- relates to #NR-424891
There's an ongoing effort to split namespaces in AC. We are using branch https://github.com/newrelic/helm-charts/tree/feat/splitNamespace from this repo to test that everything is still working. I created a separated branch on top of it that includes the changes of this PR. You can find it https://github.com/newrelic/helm-charts/tree/poc-temp-folder. This is the one I used to test that everything is still working.
=> [agent-control-deployment] improve security

charts/nr-k8s-otel-collector/Chart.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrole.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrolebinding.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset-configmap.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment-configmap.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/secret.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/service.yaml, charts/nr-k8s-otel-collector/examples/k8s/rendered/serviceaccount.yaml, charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml, charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml, charts/nr-k8s-otel-collector/values.yaml
Adds this block
```
- key: newrelic.entity.type
action: upsert
value: "k8s"
```
and removes the service.name and service_name from the metric attributes.
- fixes #
=> [nr-k8s-otel] Enable newrelic entity type to spare entity synthesis when service.name is present

charts/agent-control-deployment/Chart.yaml, charts/agent-control-deployment/templates/namespace-agents.yaml, charts/agent-control-deployment/tests/configmap_agentcontrol_config_test.yaml, charts/agent-control-deployment/tests/namespace_agentcontrol_test.yaml
No
Addresses an issue where, if the AC namespace and the sub-agents namespace were the same, the chart wasn't able to be installed.
This would happen due to Helm rendering the sub-agents namespace manifest and then `--create-namespace` for a namespace with the same name taking into effect, so Helm would later attempt to apply the rendered namespace manifest to create a namespace that already exists.
The fix introduces an additional check that disables the render of the namespace manifest if the namespace it will attempt to create is the same as the release manifest. This way Helm can be passed the `--create-namespace` as expected for the AC installation command.
=> [agent-control-deployment] fix: do not render namespace manifest if target is release namespace

charts/agent-control/Chart.yaml, charts/agent-control/templates/namespace-agents.yaml
No
Addresses an issue where, if the AC namespace and the sub-agents namespace were the same, the chart wasn't able to be installed.
This would happen due to Helm rendering the sub-agents namespace manifest and then --create-namespace for a namespace with the same name taking into effect, so Helm would later attempt to apply the rendered namespace manifest to create a namespace that already exists.
The fix introduces an additional check that disables the render of the namespace manifest if the namespace it will attempt to create is the same as the release manifest. This way Helm can be passed the --create-namespace as expected for the AC installation command.
=> [agent-control] fix: do not render namespace manifest if target is release namespace

charts/agent-control-deployment/Chart.yaml, charts/agent-control-deployment/README.md, charts/agent-control-deployment/templates/_helpers.tpl, charts/agent-control-deployment/templates/deployment-agentcontrol.yaml, charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml, charts/agent-control-deployment/templates/secret-sa-auth.yaml, charts/agent-control-deployment/tests/preinstall_job_test.yaml, charts/agent-control-deployment/values.yaml
no
It removes:
- the possibility to configure the key of the secret where some config are fetched from. 
This feature it adds complexity without a real benefit.
- it is no longer templating the secret for userKey and mounting it as an environment variables
-  related code functions and tests
=> [agent-control-deployment] cleaning unused code and features

charts/agent-control-deployment/Chart.yaml, charts/agent-control-deployment/README.md, charts/agent-control-deployment/templates/_helpers.tpl, charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml, charts/agent-control-deployment/tests/preinstall_job_test.yaml, charts/agent-control-deployment/values.yaml
no
It adds a new way to authenticate `identityClientAuthToken`. It leverage the same clientID and it allows using a local L2 to authenticate and pass just the token
=> feat(clientIDAuthToken): support managing locally the token creation

charts/agent-control-deployment/Chart.yaml, charts/agent-control-deployment/values.yaml
Bumps AC to 0.44.0 and https://github.com/newrelic/helm-charts/pull/1790/files
=> [agent-control-deployment] chore: bump AC release 0.44.0

charts/agent-control/Chart.yaml, charts/agent-control/README.md, charts/agent-control/templates/install-flux.yaml, charts/agent-control/templates/uninstall-flux.yaml, charts/agent-control/tests/install_flux_test.yaml, charts/agent-control/values.yaml
no
it introduce extra variables  and volumes for the install job of flux
Uppgrade is breaking since I am changing the installerJob var name
=> [agent-control] update proxy test

charts/agent-control-deployment/Chart.yaml, charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
no
there is already the hook policy to delete the resource, there is no reason to rely on the TTL 
=> [agent-control-deployment] removing ttl from job

charts/agent-control/Chart.yaml, charts/agent-control/README.md, charts/agent-control/values.yaml
No
Bump AC chart version due to bump in agent-control-deployment chart version
=> [agent-control] chore: bump version

.github/workflows/agent-control-e2e.yml, CODEOWNERS
Adds a workflow to run e2e test whenever any of the Agent Control charts are modified.
=> [agent-control] test: add AC e2e test workflow

.github/workflows/post-release-nri-bundle.yml
NO
AWS recently updated some paths in their eks-anywhere repo, which broke our GHA to update eks-anywhere. This fixes the GHA to match.
AWS PR for reference: https://github.com/aws-samples/eks-anywhere-addons/pull/396
=> fix: update eks-cloud paths to match aws updates
