- CODEOWNERS
I'm adding myself to be assigned to the PR reviews.
> Add alejandrodnm to CODEOWNERS

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
- charts/nri-kube-events/ci/test-values.yaml
- charts/nri-kube-events/templates/NOTES.txt
- charts/nri-kube-events/templates/_helpers.tpl
- charts/nri-kube-events/templates/clusterrole.yaml
- charts/nri-kube-events/templates/clusterrolebinding.yaml
- charts/nri-kube-events/templates/configmap.yaml
- charts/nri-kube-events/templates/deployment.yaml
- charts/nri-kube-events/templates/secret.yaml
- charts/nri-kube-events/templates/serviceaccount.yaml
- charts/nri-kube-events/values.yaml
> [charts/nri-kube-events] imported

- charts/nri-prometheus/.helmignore
- charts/nri-prometheus/Chart.yaml
- charts/nri-prometheus/README.md
- charts/nri-prometheus/ci/test-values.yaml
- charts/nri-prometheus/templates/NOTES.txt
- charts/nri-prometheus/templates/_helpers.tpl
- charts/nri-prometheus/templates/clusterrole.yaml
- charts/nri-prometheus/templates/clusterrolebinding.yaml
- charts/nri-prometheus/templates/configmap.yaml
- charts/nri-prometheus/templates/deployment.yaml
- charts/nri-prometheus/templates/secret.yaml
- charts/nri-prometheus/templates/serviceaccount.yaml
- charts/nri-prometheus/values.yaml
> [charts/nri-prometheus] imported

- charts/newrelic-mutation-webhook/Chart.yaml
- charts/newrelic-mutation-webhook/OWNERS
- charts/newrelic-mutation-webhook/README.md
- charts/newrelic-mutation-webhook/templates/NOTES.txt
- charts/newrelic-mutation-webhook/templates/_helpers.tpl
- charts/newrelic-mutation-webhook/templates/clusterrole.yaml
- charts/newrelic-mutation-webhook/templates/clusterrolebinding.yaml
- charts/newrelic-mutation-webhook/templates/deployment.yaml
- charts/newrelic-mutation-webhook/templates/job.yaml
- charts/newrelic-mutation-webhook/templates/mutationwebhookconfiguration.yaml
- charts/newrelic-mutation-webhook/templates/service.yaml
- charts/newrelic-mutation-webhook/templates/serviceaccount.yaml
- charts/newrelic-mutation-webhook/values.yaml
> [charts/newrelic-metadata-injection] imported

- README.md
> Add WIP notice to installation instructions

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
Acknowledge all the past contributors of the newrelic-infrastructure chart while it was being developed in the official Helm charts repository.
> [newrelic-infrastructure]Add contributors notice 

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/templates/daemonset.yaml
- charts/newrelic-infrastructure/values.yaml
Adds support for easily setting the k8s integration to send data to staging.
- fixes #
> [newrelic-infrastructure] staging support

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/templates/daemonset.yaml
- charts/newrelic-logging/values.yaml
No.
Updates the New Relic Fluentbit plugin to 1.3.0 and improve the templates to grab the version by default from the AppVersion in the Chart.yaml file.
> [newrelic-logging] Update logging chart and improve version templating

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/templates/daemonset.yaml
Adds the prefix `NRIA_` to the `STAGING` env var, both work but this makes it more cleat that it's an agent option.
- fixes #
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[mychartname]`)
> Prefix STAGING env var with NRIA_

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
> [newrelic-infrastructure] Changed nri-rabbitmq to nri-redis to avoid confusion

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
- charts/nri-kube-events/templates/_helpers.tpl
- charts/nri-kube-events/templates/deployment.yaml
Add nrStaging as global variable
- fixes #
> [nri-kube-events] nrStaging as global variable

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/templates/mutationwebhookconfiguration.yaml
- charts/nri-metadata-injection/values.yaml
Fix namespaceSelector indentation
- fixes https://github.com/newrelic/helm-charts/issues/57
> [nri-metadata-injection] Fix namespaceSelector indentation

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/README.md
- charts/nri-metadata-injection/templates/deployment.yaml
- charts/nri-metadata-injection/values.yaml
No
* Adding priority class support to `nri-metadata-injection`
> [nri-metadata-injection] Add priority class support

- README.md
- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/README.md
No
Update documentation on README.md so that we have all the installation/configuration documentation in one place.
- Updates README.md
> [newrelic-logging] Moves installation/configuration/uninstallation documentation to README.md

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
No.
Fixing some typos in default values.
> [newrelic-infra] Fix typo in default values

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/README.md
- charts/nri-metadata-injection/values.yaml
- fixes #
- [ x] Chart Version bumped
- [ x] Title of the PR starts with chart name (e.g. `[mychartname]`)
> [nri-metadata-injection] Update image to 1.3.0

- charts/nri-prometheus/Chart.yaml
no
bumps nri-prometheus app version
- fixes #
> [nri-prometheus] bumped chartVersion to 1.2.1 and appVersion to 2.1.0

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/README.md
- charts/nri-metadata-injection/templates/deployment.yaml
- charts/nri-metadata-injection/values.yaml
No
Configurable image pull secret
> [nri-metadata-injection] Configurable image pull secret

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/README.md
- charts/newrelic-logging/templates/daemonset.yaml
- charts/newrelic-logging/values.yaml
No
Configurable image pull secret
>  [newrelic-logging] Configurable image pull secret

- CODEOWNERS
no
Hey! Seeing I'm no longer with New Relic, I'd prefer to not be notified of every change 😛 I've removed myself from the CODEOWNERS file
> Removed Jorik from codeowners

- CODEOWNERS
> codeowners: add @roobre

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/README.md
No
We are documenting our support for proxy
- fixes #
> [newrelic-logging] Documentation for proxy support

- README.md
Changed the header to Community Plus.
- fixes #
> Update README.md with Community Plus header

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/templates/daemonset-windows.yaml
- charts/newrelic-infrastructure/templates/daemonset.yaml
- charts/newrelic-infrastructure/values.yaml
> [newrelic-infrastructure] Added annotations for DaemonSet on both Linux & Windows nodes

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
- charts/nri-kube-events/templates/deployment.yaml
- charts/nri-kube-events/values.yaml
> [nri-kube-events] Added ability to annotate Deployment

- .github/workflows/release.yml
No
Upgrades `helm/chart-releaser-action` to the latest released version.
> upgrade helm/chart-releaser-action

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
bump newrelic-infrastructure dependency.
- fixes #
> [nri-bundle]bump nri-bundle dependencies

- charts/nri-bundle/Chart.yaml
No
Generate 2.7.1 release since 2.7.0 [was removed ](https://github.com/newrelic/helm-charts/commit/2e47fc5609a81250d5ca01d4dbb7a64acddb25cd)
- fixes #
> [nri-bundle] bump nri-bundle minor version to generate new release

- index.yaml
We noticed a bug in the CI that deleted one of the last releases. This Pr restore it
> Restore Chart into the index

- .github/workflows/release.yml
> validate remote index.yaml with the local one

- charts/synthetics-minion/Chart.yaml
[charts/synthetics-minion] the following changes were done:
- **appVersion** bumped from **3.0.42** to **3.0.45**
> [charts/synthetics-minion] Bumped appVersion to 3.0.45

- .gitignore
> fix(gitignore): the missing slash was causing all values to be ignored

- charts/newrelic-pixie/Chart.yaml
No.
Updates the app version to `0.1.1`
> [newrelic-pixie] Bump app version to 0.1.1

- charts/newrelic-pixie/Chart.yaml
No.
Updates the app version to `0.1.2`
> [newrelic-pixie] Bump app version to 0.1.2

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No.
Updates the bundled version of `newrelic-pixie` to `0.1.0-alpha.3`.
> [nri-bundle] Bump the bundled version of newrelic-pixie to 0.1.0-alpha.3

- charts/newrelic-pixie/Chart.yaml
- charts/newrelic-pixie/README.md
- charts/newrelic-pixie/values.yaml
No
* Update to the latest Pixie helm chart and updates the Pixie integration.
* Sets the limits for the Pixie integration a bit higher.
* Updates the pull policy.
> [newrelic-pixie] Update to the latest version, increase limits & update pull policy.

- charts/newrelic-pixie/Chart.yaml
No.
Update to the latest version of the Pixie integration.
License key issue in v0.1.3 in the integration.
> [newrelic-pixie] Update to the latest version.

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
No.
Update the bundle to include the latest version of the newrelic-pixie chart.
License key issue in the New Relic Pixie integration.
> [nri-bundle] Update newrelic-pixie to the latest version in the bundle.

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
- charts/nri-bundle/values.yaml
yes
In order to add newrelic-infra-operator chart to the bundle
- fixes https://github.com/newrelic/helm-charts/issues/333
- fixes https://github.com/newrelic/helm-charts/issues/360
> [nri-bundle] Adding chart for operator

- charts/newrelic-pixie/Chart.yaml
No
Update to the latest version of the Pixie integration.
Adds data limiting options in v0.1.6 of the integration.
> [newrelic-pixie] Update to the latest version for the Pixie integration.

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/rolebinding.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/serviceaccount.yaml
- charts/nri-metadata-injection/templates/cert-manager.yaml
no
Namespaced resources should have the namespace indicated
> [nri-metadata-injection] adding namespace to resources

- charts/newrelic-infra-operator/Chart.yaml
- charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/job-createSecret.yaml
- charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/role.yaml
- charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/rolebinding.yaml
- charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/serviceaccount.yaml
- charts/newrelic-infra-operator/templates/cert-manager.yaml
- charts/newrelic-infra-operator/templates/configmap.yaml
- charts/newrelic-infra-operator/templates/deployment.yaml
- charts/newrelic-infra-operator/templates/secret.yaml
- charts/newrelic-infra-operator/templates/service.yaml
- charts/newrelic-infra-operator/templates/serviceaccount.yaml
no
- fix namespace
- fix cert-manager 
> [newrelic-infra-operator] adding namespace to resources

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/values.yaml
> nri-kube-events: upgrade forwarder image to 1.18.0

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/templates/deployment.yaml
- charts/nri-metadata-injection/values.yaml
> nri-metadata-injection: upgrade to 1.5.0

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
> nri-bundle: upgrade charts to their latest versions

- CODEOWNERS
> chore: caos to own statsd

- charts/newrelic-infrastructure/Chart.yaml
- Update infra agent to last version.
> Update infra agent to last version

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/templates/deployment.yaml
no
fix https://github.com/newrelic/helm-charts/issues/407
- fixes https://github.com/newrelic/helm-charts/issues/407
> [nri-kube-events] removed duplicated keys and updated maintainers

- .github/workflows/lint_test_charts.yaml
- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/clusterrole.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/role.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/rolebinding.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/job-patch/serviceaccount.yaml
- charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
no
To fix https://github.com/newrelic/helm-charts/issues/408
- fixes https://github.com/newrelic/helm-charts/issues/408
> [nri-metadata-injection]  removed duplicate keys and updated maintainers

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
no
Fix https://github.com/newrelic/helm-charts/issues/239
- fixes https://github.com/newrelic/helm-charts/issues/239
> [newrelic-infrastructure] Clarify documentation

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No.
Bump a bunch of dependencies in the bundle chart.
> [nri-bundle] Bump dependencies

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
- Update the kube-events version in the bundle
> Update nri-kube-events version in bundle

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
Adds to the bundle dependencies pixie
> [nri-bundle] stable pixie release

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
bumps nri-kube-events and newrelic-infra version
- fixes #
> [nri-bundle] Bump nri-kube-events, newrelic-infra version

- charts/newrelic-pixie/Chart.yaml
No.
Upgrades the version of the integration's image.
> [newrelic-pixie] Upgrade the appVersion

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No.
Updates the included newrelic-pixie chart to version v1.1.0
> [nri-bundle] Bump newrelic-pixie chart to 1.1.0

- charts/newrelic-infrastructure/Chart.yaml
> [newrelic-infrastructure] bump app version to 2.7.0

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
bumps k8s integration chart
- fixes #
> [nri-bundle] bump newrelic-infrastrucutre to 2.6.0

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
> nri-bundle: update to latest infrastructure-bundle

- charts/synthetics-minion/Chart.yaml
- charts/synthetics-minion/README.md
- charts/synthetics-minion/templates/_helpers.tpl
- charts/synthetics-minion/templates/statefulset.yaml
- charts/synthetics-minion/values.yaml
No
This PR allows users to add custom labels and annotations to minions pods.
- fixes # N/A
Thank you!
> [synthetics-minion] Add custom labels and annotations for minions pods

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/README.md
no
fix https://github.com/newrelic/helm-charts/issues/487
> [nri-metadata-injection] fix docs example command

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
bumps charts to latest version:
- metadata-injection 
- pixie 
- infra-operator charts
- fixes #
> [nri-bundle] bumps dependencies

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No
See - https://github.com/newrelic/helm-charts/pull/500
this updates nri-bundle to use the latest
- fixes #
> [chart/nri-bundle] bump newrelic-pixie dependency

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
No
Configuring the infrastructure agent through Helm is often not clear enough for some users. This PR adds more verbosity to the config examples to hopefully be more clear in how to achieve this.
> nri-bundle: clarify how to configure dependencies and the agent

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
bumps infra version
- fixes #
> [nri-bundle] newrelic-infra dependency update

- charts/synthetics-minion/Chart.yaml
No
Last release we inadvertently downgraded the chart version instead of bumping it up. Making this change to get it back to the intended version.
- fixes #
> [synthetics-minion] Correct the release version

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/templates/configmap.yaml
No
Fixes log collection when running on lowDataMode.
> [newrelic-logging] Fixes config map to not exclude the original message from the payload when running in lowDataMode

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No
Updates the nri-bundle to use the latest version of newrelic-logging, which fixes an important bug.
> [nri-bundle] Updates newrelic-logging to the latest version

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No
Updates versions of nri-metadata-injection and newrelic-logging.
> [nri-bundle] Updates versions in nri-bundle

- charts/synthetics-minion/Chart.yaml
Manually updates the Minion version, as the automatic update failed
No
Manually updates the Synthetics Minion Chart to the correct version, as the automatic update did not work.
- fixes #
> Synthetics Minion Change

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/templates/daemonset.yaml
- Fix yaml indentation error in override short
> Fix yaml indentation error in override short

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
- Bump bundle version to 2.7.2
> Bump bundle version to 2.7.2

- charts/newrelic-k8s-metrics-adapter/Chart.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/clusterrole.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/clusterrolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-createSecret.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-patchAPIService.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/psp.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/role.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/rolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/serviceaccount.yaml
- charts/newrelic-k8s-metrics-adapter/values.yaml
no
Fix install failing due to labels containing more than 63 chars.
- fixes #
> [newrelic-k8s-metrics-adapter] fix labels length

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No
Bump newrelic-logging and newrelic-k8s-metrics-adapter to latest versions, as discussed in #583 
> [nri-bundle] Bump newrelic-logging and newrelic-k8s-metrics-adapter

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
Signed-off-by: smcavallo <smcavallo@hotmail.com>
https://github.com/pixie-io/pixie/commit/8b71cfc01ae074d55f182a38a58348c2ad7bdf32
https://github.com/pixie-io/pixie/commit/ea6070e6484c7c0c1dde517187d58cd35a0eac49
- fixes #
> [nri-bundle] upgrade pixie-operator-helm2-chart

- charts/synthetics-minion/Chart.yaml
> Update chart version.

- charts/synthetics-minion/Chart.yaml
> Add more reviewers

- charts/newrelic-infrastructure-v3/Chart.yaml
- charts/newrelic-infrastructure-v3/templates/control-plane/configmap.yaml
- charts/newrelic-infrastructure-v3/templates/control-plane/daemonset.yaml
- charts/newrelic-infrastructure-v3/templates/ksm/configmap.yaml
- charts/newrelic-infrastructure-v3/templates/ksm/deployment.yaml
- charts/newrelic-infrastructure-v3/templates/kubelet/configmap.yaml
- charts/newrelic-infrastructure-v3/templates/kubelet/daemonset.yaml
> [newrelic-infrastructure-v3] Fix configuration file location

- charts/newrelic-infrastructure-v3/Chart.yaml
- charts/newrelic-infrastructure-v3/templates/control-plane/daemonset.yaml
- charts/newrelic-infrastructure-v3/templates/ksm/deployment.yaml
- charts/newrelic-infrastructure-v3/templates/kubelet/daemonset.yaml
no
removing a the tmp volumes
- fixes #
Linked to https://github.com/newrelic/nri-kubernetes/pull/305. In store memory should allow not having to mount tmp folder
> [newrelic-infrastructure-v3] remove tmp volume

- charts/newrelic-logging/Chart.yaml
Bump logging helm chart version.
Automation process
> [newrelic-logging] Bump logging helm chart version

- charts/newrelic-k8s-metrics-adapter/Chart.yaml
no
updating metric adapter image
- fixes #
> [newrelic-k8s-metric-adapter] updating metric adapter image

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
Updates bundle with new charts
> [nri-bundle] updating dependencies

- charts/newrelic-infrastructure-v3/Chart.yaml
- charts/newrelic-infrastructure-v3/README.md
- charts/newrelic-infrastructure-v3/values.yaml
no
bumps forwarder and bundle image
> feat(infraV3): update images to leverage customAttributes

- charts/newrelic-infrastructure-v3/Chart.yaml
- charts/newrelic-infrastructure-v3/values.yaml
No
Adds an autodiscovery endpoint for the API Server Control Plane component that matches the Kind cluster in order to automatically detect this component.
- fixes #
> [newrelic-infrastructure-v3] add API Server metrics endpoint for Kind cluster

- charts/newrelic-infrastructure-v3/Chart.yaml
- charts/newrelic-infrastructure-v3/README.md
- charts/newrelic-infrastructure-v3/values.yaml
> [newrelic-infrastructure-v3] update images with stable ones

- README.md
Not a new chart, an update to the README
A link to helm-hub that works 🎉 
N/A
~- [ ] Chart Version bumped~
~- [ ] Variables are documented in the README.md~
~- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)~
> chore(README): Update artifact hub link

- index.yaml
Updating manually chart release from fork to include beta release
> [chart-index] update manually

- charts/newrelic-infrastructure-v3/Chart.yaml
- charts/newrelic-infrastructure-v3/README.md
- charts/newrelic-infrastructure-v3/templates/_helpers.tpl
- charts/newrelic-infrastructure-v3/templates/controlplane/daemonset.yaml
- charts/newrelic-infrastructure-v3/templates/ksm/deployment.yaml
- charts/newrelic-infrastructure-v3/templates/kubelet/daemonset.yaml
- charts/newrelic-infrastructure-v3/tests/annotations_test.yaml
- charts/newrelic-infrastructure-v3/tests/initContainers_test.yaml
- charts/newrelic-infrastructure-v3/tests/nodeAffinity_test.yaml
- charts/newrelic-infrastructure-v3/tests/nodeSelectors_test.yaml
- charts/newrelic-infrastructure-v3/tests/roleBinding_control_plane_test.yaml
- charts/newrelic-infrastructure-v3/tests/securityContext_test.yaml
- charts/newrelic-infrastructure-v3/values.yaml
no
adding init containers needed in some scenarios
related to https://github.com/newrelic/newrelic-coreint/issues/291
> [newrelic-infrastructure-v3] init container

- index.yaml
> [gh-pages] New beta version

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_library_priority_class_name_test.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_priority-class-name.tpl
no
adding priorityClassName to common library
> [common-library] priorityClassName

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/tests/common_images_registrty_test.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_images.tpl
no
.context.Values.global.image could have been nil with global defined 
- fixes #
> [common-library] nil pointer

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_library_nodeselector_test.yaml
- library/CHART-TEMPLATE/values.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_nodeselector.tpl
No
Adds `common.nodeSelector` helper to common library
- fixes #
> [common-library] add global.nodeSelector 

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_library_labels_test.yaml
- library/CHART-TEMPLATE/tests/common_library_pod_labels_test.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_labels.tpl
no
add support in common library for podLabels and labels
- [] Variables are documented in the README.md
> [common-library] labels

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_library_tolerations_test.yaml
- library/CHART-TEMPLATE/values.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_tolerations.tpl
No
Adds common.tolerations to the common library
- fixes #
> [common-library] add common.tolerations

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_library_affinity_test.yaml
- library/CHART-TEMPLATE/values.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_affinity.tpl
No
Add Affinity common helper to library
- fixes #
> [common-library] add common.affinity

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_library_proxy_test.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_proxy.tpl
No
Adds the `common.proxy` helper to the library
- fixes #
> [common-library] Add common.proxy

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_library_fedramp_test.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_fedramp.tpl
No
Adds fedramp helper to library
- fixes #
> [common-library] Add common.fedramp

- library/CHART-TEMPLATE/Chart.lock
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/templates/deployment.yaml
- library/CHART-TEMPLATE/tests/common_images_security_context_container_test.yaml
- library/CHART-TEMPLATE/tests/common_images_security_context_pod_test.yaml
- library/common-library/Chart.yaml
- library/common-library/templates/_security-context.tpl
no
Add to globals and library the security context
> [common-library] global for security context

- index.yaml
Updating index manually from fork to include beta
> chore(gh-pages): updating index manually

- library/common-library/Chart.yaml
- library/common-library/templates/_images.tpl
Properly format some functions comments in common-library
> chore: properly format function comments

- charts/nri-prometheus/Chart.yaml
no
Update integration version to 2.15.0
- fixes #
> [nri-prometheus] Update nri-prometheus to 2.15.0

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
no
- `nri-prometheus` 1.13.2 -> 1.14.0
- `newrelic-infrastructure` 2.9.0 -> 2.10.0
- `newrelic-infra-operator` 0.5.0 -> 0.6.0
- fixes #
For some reason some of the charts were outdated in the `requirements.yaml` file but with the new version in the lock file.
> [nri-bundle] Update bundle dependencies

- index.yaml
no
updating manually index for beta
> chore(index): pointing to new beta

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/requirements.lock
- charts/nri-bundle/requirements.yaml
No
- fixes #https://github.com/newrelic/newrelic-k8s-metrics-adapter/pull/60
> [nri-bundle]: Update nri-bundle metrics-adapter dependency

- charts/newrelic-pixie/Chart.yaml
No
Update Pixie integration to 1.5.0
> [newrelic-pixie] Update to v1.5.0 of the integration

- charts/nri-bundle-legacy/Chart.yaml
- charts/nri-bundle-legacy/README.md
- charts/nri-bundle-legacy/values.yaml
- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- charts/nri-bundle/values.yaml
- fixes #576
~~Tests are not passing because chart-linter simply sees if there are files changing: https://github.com/helm/chart-testing/blob/3c014d8d385ae03dc9e040c93ce71bcdf76a38eb/pkg/tool/git.go#L58-L68~~
~~There is no logic changed in this chart and there is no need to bump the version because of a change in the documentation.~~
We have to bump versions because if not next PR is going to break in the same way this one is breaking.
> [nri-bundle] Remove unused variables from values and README

- .github/workflows/release.yml
No
We want that contributors run pipelines inside this repo to be able to test their changes. They would have to patch their repository to make the pipeline work so that makes the contribution harder as they have to patch, run and unpatch.
This PR should solve that issue.
> [CI/CD] Make this repository forkable

- charts/synthetics-minion/Chart.yaml
> bumped chart version to 1.0.51 + appVersion to 3.0.65

- charts/nri-bundle/Chart.lock
- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- charts/nri-bundle/README.md.gotmpl
Update nri-bundle dependencies so all of them use latests common.library version which includes verboseLog new behaviour. See #874 for details.
fixes #869 
> nri-bundle: chore(deps): bump nri-bundle dependencies

- charts/nri-bundle/Chart.lock
- charts/nri-bundle/Chart.yaml
No
Upgrade all the charts affected by #875
- fixes #875
> [nri-bundle] Upgrade nri bundle and update all the dependencies

- charts/newrelic-pixie/Chart.yaml
- charts/nri-bundle/Chart.yaml
Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>
No
> [newrelic-pixie] Update version to 2.0.1

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/templates/job.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/templates/deployment.yaml
- charts/synthetics-job-manager/ci/default-values.yaml
- charts/synthetics-job-manager/templates/deployment.yaml
- charts/synthetics-job-manager/values.yaml
No
Update new synthetics-job-manager helm chart with fixes and version adjustments
- fixes #
> [synthetics-job-manager] - next gen fixes

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- charts/nri-bundle/README.md.gotmpl
`false`
Adds instructions to the README on how to bring your own KSM instance.
- fixes #
> nri-bundle: README: add byoksm instructions

- charts/nri-bundle/Chart.lock
- charts/nri-bundle/Chart.yaml
Update `newrelic-logging` dependency in `nri-bundle` and bump version
> Update newrelic logging in nri bundle

- charts/nri-bundle/Chart.lock
- charts/nri-bundle/Chart.yaml
Update nri-bundle with the last version of the `newrelic-infrastructure` chart https://github.com/newrelic/nri-kubernetes/pull/542.
- fixes https://github.com/newrelic/infrastructure-agent/pull/1388
> [nri-bundle]: bump newrelic-infrastructure

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/README.md
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/values.yaml
- charts/synthetics-job-manager/values.yaml
NO
This PR is so add resource limits and requests to the ping runtime. Unfortunately there is no way to test out these changes at the moment. However, the numbers used in the limits and requests came for how we run the ping runtime public. 
- fixes #
> [synthetics-job-manager]: Adding Resource Requests and Limits for Ping Runtime

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No!
Updating chart and app versions to the latest. 
Ticket: [NR-50008](https://issues.newrelic.com/browse/NR-50008) 
Double check the versions as well in the Kevin Dashboards: 
Runtime Versions: https://onenr.io/0yw4p8kqaw3
Kevin Version: https://onenr.io/0KQXAp4gdwa
- fixes #
> [synthetics-job-manager]: Updating to the latest runtimes and job manager versions

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
No
Increments the versions of the recently released Synthetics services
> [synthetics-job-manager] chore: upgrade versions of runtime and synthetics job manager

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Increments the versions of the runtimes to latest released versions.
- fixes #
> [synthetics-job-manager] chore: increment versions for release

- charts/synthetics-job-manager/Chart.yaml
No
Increments synthetics job manager release version
- Some recent issues with private job managers pulling and running images.
> [synthetics-job-manager] increment job manager version to release-168

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
sjm: release-168 -> release-183
browser: 1.1.36 -> 1.1.46
api: api-runtime: 1.1.20 -> 1.1.21
Nope
Increments the versions of the recently released Synthetics services
- fixes #
> [synthetics-job-manager] chore: upgrade sjm and runtime versions

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
NO. 
Updating the chart and release version
- fixes #
> [synthetics-job-manager] Updating SJM and node api versions

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No.
Updating the chart and release version for SJM and node-browser runtimes
- fixes #
> [synthetics-job-manager] Update SJM and node browser runtime versions

- charts/synthetics-minion/Chart.yaml
No.
**appVersion** bumped from 3.0.65 to 3.0.68
- fixes #
> [synthetics-minion] Bumped appVersion to 3.0.68

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Fixes bugs that were preventing monitors from running successfully in Kubernetes
- fixes #
> [synthetics-job-manager] update sjm/node-api/node-browser charts

- charts/newrelic-pixie/Chart.yaml
Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>
No
This updates the version of the newrelic-pixie-integration with a new feature that allows users to overwrite their license keys.
> [newrelic-pixie] Update version to 2.0.2

- .github/workflows/lint_test_charts.yaml
- scripts/check-bundle-dependencies.sh
no
Include a shell-script based check to test nri-bundle dependencies chart conditions
> test: include script to check bundle dependencies

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
It updates the appVersion of node browser runtime to latest.
- fixes #
> [synthetics-job-manager] upgrade node-browser runtime version

- .github/renovate.json5
No
Disables ksm updates in renovate settings
> chore: disable ksm updates in renovate settings

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/values.yaml
Revert https://github.com/newrelic/helm-charts/pull/998.
> Revert KSM v2 nameOverride

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
Needs this because we release new private browser runtime
- fixes #
As you can see we are on the new 1.1.74 runtime
Showing public image and private image matching
> [synthetics-job-manager] chore: update browser and api runtimes

- charts/synthetics-minion/Chart.yaml
I did a CPM deploy today so I need to update CPM chart
No
Need to update this as I did a CPM deploy today.
- fixes #
> [synthetics-minion] chore: update CPM Chart

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No.
- Updates ping-runtime ubuntu image
- Updates job manager ubuntu image
- Update node-browser runtime Transaction header format
> [synthetics-job-manager] Deploy job manager chart 208

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
This PR aims to implement the following version updates to the Synthetics Job Manager helm charts:
Job Manager: release-208 --> release-213
Node-API-Runtime: 1.1.29 --> 1.1.31
Node-Browser-Runtime: 1.1.76 --> 1.1.80
Synthetics Deployment
> [synthetics-job-manager, node-api-runtime, node-browser-runtime] Update Synthetics Job Manager and Runtime Versions

- charts/synthetics-job-manager/Chart.yaml
This PR aims to implement the following version updates to the Synthetics Job Manager helm charts:
Job Manager: release-213 --> release-215
- fixes #
> [synthetics-job-manager] Update sjm chart to release-215

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No
To update the Synthetics runtimes versions
- fixes #
> [synthetics-job-manager] update synthetics runtimes

- charts/synthetics-minion/Chart.yaml
> Synthetics-Minion Bump Minion Version

- README.md
Just came across one of the upgrade issues mentioned in the documentation. To make this information easier accessible I linked the page in the README.
- fixes #
> Add Upgrade link to README.md

- charts/newrelic-pixie/Chart.yaml
- charts/newrelic-pixie/templates/job.yaml
no
set new defaults for pixie scraping while still keeping option for low data mode (im ok if we remove low data mode altogether)
- fixes #
none
hi thanks for reviewing my chart
> [newrelic-pixie] use new default values for pixie

- charts/newrelic-pixie/Chart.yaml
No
Updates the maintainers for pixie chart
> [newrelic-pixie]: Update maintainers in chart

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
No
Updates maintainers for nri-bundle
> [nri-bundle]: Update maintainers for nri-bundle

- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/README.md
No
Updates maintainers for chart template
> [chart-template]: Update maintainers for chart template

- library/common-library/Chart.yaml
No
Update maintainers for common library
> [common-library]: Update maintainers for common library

- .github/ISSUE_TEMPLATE/bug-report.md
No
Fix typo in `.github/ISSUE_TEMPLATE/bug-report.md` that causes a codespell linting error. 
> Fix codespell linting error

- charts/newrelic-pixie/Chart.yaml
- charts/newrelic-pixie/README.md
No.
This updates the version of `newrelic-pixie-integration` to pull in some dependency updates that address known CVEs. 
> [newrelic-pixie] Update integration version to v2.0.5

- charts/nri-statsd/Chart.yaml
- charts/nri-statsd/values.yaml
> [statsd] chore: bump statsd version to 2.5.0

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Updates helm charts for Synthetics Job Manager and Node-Browser-Runtimes to address CVEs and better manage jobs that are missing scripts.
N/A
> [Synthetics Job Manager] update helm chart for sjm and node-browser-runtime

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
NO
Fixes cookie exception errors in simple browser monitors  when SSL validation is enabled.
> [Synthetics Job Manager] update synthetics node browser runtime

- charts/synthetics-minion/Chart.yaml
No
Adds the latest minion release to the helm charts
- fixes #
> [synthetics-minion] 3.0.83 CPM release

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/k8s/new-relic-fluent-plugin.yml
- Upgraded logging helm chart to v1.14.0. 
- Upgraded app version to v1.16.0
> [newrelic-logging] Upgrade logging helm chart to v1.14.0 and app version to v1.16.0

- charts/newrelic-pixie/Chart.yaml
No
Updates app and chart versions
No fix
> [newrelic-pixie] Update app and chart versions

- .github/workflows/lint_test_charts.yaml
no
https://github.com/quintush/helm-unittest
> Since the end of January 2023, a new version of the unittest plugin is published in the main repository [helm-unittest/helm-unittest](https://github.com/helm-unittest/helm-unittest).
N/A
hi
N/A
> use helm-unittest/helm-unittest

- charts/synthetics-job-manager/Chart.yaml
updates helm charts to use sjm release-257
No
Updates helm charts for Synthetics Job Manager to bugs around scripted jobs where the script is not available.
NA
> [Synthetics Job Manager] release-257

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
NO
- Upgrades Chrome to version 112.
- Proxy auth fixes for browser runtime.
N/A
> [Synthetics Job Manager] update browser runtime

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No.
- Adds CVE fixes and bug fixes for Job Manager
- Updates Ubuntu base image for Ping Runtime
- Allows Node to build crash reports in Node API Runtime
N/A
> [Synthetics Job Manager] update job manager and runtime chart versions

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No.
Helm chart to match Synthetics Release of Public Images. 
- fixes #
N/A
> synthetics-job-manager: SJM + Node Browser Runtime Image Updates. 

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
Nope.
Helm chart to match Synthetics Release of Public Images.
- fixes #
> [synthetics-job-manager]: SJM + Node Browser Runtime Updates

- charts/newrelic-pixie/Chart.yaml
No
Bump versions for pixie-integration
> [pixie-integration] Bump versions

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
no
update charts for node browser runtime
- fixes #
> [synthetics-job-manager]: node browser runtime image update

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Introduces bug fixes, CVE fixes, & updated functionality to Synthetics Job Manager Kubernetes customers.
> [Synthetics Job Manager] update chart values for sjm and node browser runtime

- charts/newrelic-pixie/Chart.yaml
It is a new pixie chart
- fixes #NR-128589
This new pixie charts only includes dependency upgrades to fix vulnerbilities
> Bump Pixie Chart Versions

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No.
Ping Runtime - Fix: Adds retry logic for the use of the OpenSSL library to check endpoint certificates.
N/A
> [Synthetics Job Manager] update ping runtime chart version

- .github/workflows/lint_test_charts.yaml
- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/templates/daemonset-windows.yaml
- charts/newrelic-logging/templates/daemonset.yaml
- charts/newrelic-logging/tests/images_test.yaml
- charts/newrelic-logging/values.yaml
By leveraging `library/common-library/templates/_images.tpl` we can propagate global settings as well as override within the chart's `values.yml`.
- fixes https://github.com/newrelic/helm-charts/issues/1057
> [newrelic-logging] Leverage common images functions

- docs/chart_testing.md
No 
I was testing out a change, and wasn't sure how to test it locally. These are the instructions I stumbled upon.
> [all]: Add instructions for running Helm unit tests locally

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
> Update issue templates

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
- charts/synthetics-minion/Chart.yaml
No. 
Just updates the chart and app version of all the charts that the Synthetics team owns.
> [synthetics-job-manager/synthetics-minion]: Updating chart and app version to reflect the latest in production

- charts/synthetics-job-manager/Chart.yaml
No
We need this so we can reach parity with the helm chart version and the public release version.
- fixes #
Helps us reach parity between helm chart and public release version.
Here are the changes between 286 -> 291:
https://source.datanerd.us/synthetics/synthetics-kevin/compare/release-286...release-291
Here is the Public release showing 291:
Production: https://onenr.io/0gR70LyyXjo
EU: https://onenr.io/0VRVoObbxja
Here is the Private release showing 291:
https://hub.docker.com/layers/newrelic/synthetics-job-manager/release-291/images/sha256-865db0f682ace06b3601e465c4d23953ba4b22dbb665e81c4951887613c79f44?context=repo
[Place an '[x]' (no spaces) in all applicable …
> [Synthetics Job Manager] Update chart values for SJM

- charts/nri-bundle/Chart.lock
- charts/nri-bundle/Chart.yaml
Updates KSM version installed with the bundle, so we can fully support the latest Kubernetes versions (>v1.23)
- fixes #1076
> [nri-bundle] Update KSM version

- .github/workflows/post-release.yml
- .github/workflows/release.yml
- .gitignore
- scripts/write-release-notes.sh
> ci: Automate weekly release of bundle

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix:  Fix 'Post-Release Tasks' workflow

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix: Add multiline support for output variables

- charts/nri-bundle/Chart.yaml
- scripts/write-release-notes.sh
> ci: Improve Slack announcement

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> feat: Update public docs

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix: Change single quotes to allow to allow interpolation

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix: Use correct token

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix: Correct token enables scripts to run authenticated git commands

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix: Use double quotes to avoid shell interpolation

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix: Use correct base branch

- .github/workflows/post-release.yml
- charts/nri-bundle/Chart.yaml
> fix: Address 'baseRefName is invalid' error

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Updates charts for Synthetics Job Manager and Node Browser Runtime for latest release.
- fixes #
> [synthetics-job-manager] update job manager (release-298) and node browser (2.0.35) versions

- .github/workflows/release.yml
> ci: Finalize schedule for nri-bundle release

- .github/workflows/post-release-nri-bundle.yml
> ci: Rename workflow to make clear it only affects nri-bundle

- .github/workflows/post-release-nri-bundle.yml
> [nri-bundle] Update EKS Sleek repo with latest nri-bundle version

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No
Update ping runtime version
> [synthetics-job-manager] ping runtime deploy

- .github/workflows/post-release-nri-bundle.yml
No
Replace single quotes with double quotes to fix error with reading env var `${version}`
- fixes #
> fix: Fix post release nri-bundle workflow

- .github/workflows/post-release-nri-bundle.yml
> [nri-bundle] Fix 'Post-Release Tasks (nri-bundle)' workflow

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/ci/test-values.yaml
- charts/super-agent-deployment/templates/deployment-superagent.yaml
- charts/super-agent-deployment/tests/configmap_config_test.yaml
- charts/super-agent-deployment/values.yaml
> [super-agent-deployment] fix(SA): remove deprecated running_mode

- .github/workflows/post-release-nri-bundle.yml
Fix this workflow warning:
```
Error while fetching latest Helm release: Error: [@octokit/auth-action] `GITHUB_TOKEN` variable is not set. It must be set on either `env:` or `with:`. See https://github.com/octokit/auth-action.js#createactionauth. Using default version v3.9.0
```
- fixes #
> [nri-bundle] Fix workflow warning message

- .github/workflows/lint_test_charts.yaml
- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
Use the `--no-doc` flag to avoid printing document separators (`---`)
- fixes #
> [nri-bundle] Fix check for common library versions

- .github/workflows/post-release-nri-bundle.yml
Update token permissions to be able to access forks owned by the bot account
- fixes #
> [nri-bundle] Update token permissions for forks

- charts/nri-bundle/Chart.yaml
> [nri-bundle] Trigger release

- .github/workflows/post-release-nri-bundle.yml
- charts/nri-bundle/Chart.yaml
> [nri-bundle] Fix token permissions

- .github/workflows/post-release-nri-bundle.yml
- charts/nri-bundle/Chart.yaml
Using correct token permissions to get workflow to work
- fixes #
> [nri-bundle] Use correct token permissions

- .github/workflows/post-release-nri-bundle.yml
- charts/nri-bundle/Chart.yaml
Use correct token permissions for AWS
- fixes #
> [nri-bundle] Use correct token permissions for AWS

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
> [synthetics-job-manager] runtime updates

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Updating the app version for node-browser runtime
> [synthetics-job-manager] add release notes for node-browser runtime 2.1.10

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No.
Updates the browser runtime to the latest public version.
- fixes #
> Synthetics-job-manager: Browser runtime release

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/templates/deployment-superagent.yaml
- charts/super-agent-deployment/templates/rbac.yaml
- charts/super-agent-deployment/tests/deployment_superagent_subagent_configs_test.yaml
No
Fixes issues founded during manual testing
- fixes rbac missing
- fixes CM of sub-agent naming
> [super-agent-deployment] fixes

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No, updating existing chart.
Updates the node-browser-runtime version that the Synthetics Private Job Manager will utilize.
- fixes Chrome version that customers have access to to Chrome 117
> [synthetics-job-manager] feat: Update Synthetics Job Manager and Browser-Runtime Charts

- .github/workflows/post-release-nri-bundle.yml
> [nri-bundle] feat: Update Slack channel

- charts/synthetics-job-manager/Chart.yaml
No.
Updates SJM version from 321 to 326.
- fixes #
> [synthetics-job-manager] feat: Update SJM version from 321 to 326

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/templates/configmap-subagent-configs.yaml
- charts/super-agent-deployment/templates/deployment-superagent.yaml
- charts/super-agent-deployment/tests/configmap_fleet_configs_test.yaml
- charts/super-agent-deployment/tests/deployment_superagent_subagent_configs_test.yaml
Fix sub agent expected config path
- fixes #
> [super-agent-deployment] Fix subagent path

- .github/renovate.json5
> chore: Update Renovate config file

- .github/renovate.json5
> chore: Enable all managers

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/README.md
- charts/super-agent-deployment/values.yaml
Creating a semi-stable beta release
Related to https://github.com/newrelic/newrelic-super-agent/pull/389
> [super-agent-deployment] Fixing image to 0.7.0

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Updates release versions for synthetics-job-manager, node-browser-runtime, and node-api-runtime.
> [synthetics-job-manager] chore: update synthetics-job-manager, node-browser-runtime, and node-api-runtime releases

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/values.yaml
- charts/synthetics-job-manager/values.yaml
No
* Updates chart for SJM release-337
* Increases default resource request/limits for node-browser-runtime
> [Synthetics Job Manager] update default resources for node-browser-runtime and release-337 for sjm

- charts/super-agent/Chart.yaml
- charts/super-agent/templates/_helm-release.yaml
- charts/super-agent/values.yaml
use `disableWait` to unblock modification/deletion of the HelmRelease
- fixes #
> [super-agent] feat: disableWait for SA installation

- .github/workflows/post-release-nri-bundle.yml
> [nri-bundle] chore: Update EKS Sleek repo job

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/README.md
- charts/super-agent-deployment/templates/uninstall-job.yaml
Fixes a typo in the super-agent-deployment uninstall job.
> [super-agent-deployment] fix uninstall job script

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
NO.
Updates Synthetics Images to the latest versions on Github. 
SJM: https://hub.docker.com/r/newrelic/synthetics-job-manager/tags 
Ping Runtime: https://hub.docker.com/r/newrelic/synthetics-ping-runtime/tags
Browser Runtime: https://hub.docker.com/r/newrelic/synthetics-node-browser-runtime/tags
API Runtime: https://hub.docker.com/r/newrelic/synthetics-node-api-runtime/tags
- fixes #
N/A
> synthetics-job-manager - Using latest Synthetics Images.

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/README.md
- charts/super-agent-deployment/values.yaml
> [super-agent-deployment] updated to 0.8.0

- charts/super-agent/Chart.yaml
- charts/super-agent/README.md
- charts/super-agent/values.yaml
> [super-agent] updated subchart to 0.12.0

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
No
Updates all runtime app versions, including some important bug fixes
> [synthetics job manager] update helm chart for SJM (all runtimes)

- charts/synthetics-job-manager/Chart.yaml
No
Update helm charts with latest synthetics-job-manager version: release-341
- fixes #
> [Synthetics-job-manager] Update helm chart for SJM

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
No
Since we did a private deploy for the node api runtime, we need to update the helm chart.
Proof of private deploy: https://hub.docker.com/r/newrelic/synthetics-node-api-runtime/tags
> [synthetics job manager] update helm chart for node api runtime

- charts/newrelic-pixie/Chart.yaml
- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- library/CHART-TEMPLATE/Chart.yaml
- library/CHART-TEMPLATE/README.md
- library/common-library/Chart.yaml
> chore: Update chart maintainers

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/README.md
> [synthetics-job-manager] re-add maintainers

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/README.md
- charts/super-agent-deployment/templates/_helpers.tpl
- charts/super-agent-deployment/templates/configmap-subagent-configs.yaml
- charts/super-agent-deployment/templates/configmap-superagent-config.yaml
- charts/super-agent-deployment/templates/deployment-superagent.yaml
- charts/super-agent-deployment/tests/configmap_fleet_configs_test.yaml
- charts/super-agent-deployment/tests/configmap_superagent_config_test.yaml
- charts/super-agent-deployment/tests/deployment_superagent_subagent_configs_test.yaml
- charts/super-agent-deployment/values.yaml
no
This PR depends on https://github.com/newrelic/newrelic-super-agent/pull/525 and is used there already for e2e test, we should not merge it for now
> [super-agent-deployment] Removing volume mounts

- charts/synthetics-minion/Chart.yaml
No
Includes latest CPM release
- fixes #
> chore: update chart for latest CPM release

- charts/synthetics-job-manager/Chart.yaml
> Updates Synthetics Job Manager chart to release-368

- charts/synthetics-job-manager/Chart.yaml
No
revs sjm release to release-370 to include runtime upgrade validation support for step monitors.
- fixes #
> [synthetics-job-manager] release-370

- .github/workflows/post-release-nri-bundle.yml
> [nri-bundle] feat: Update EKS Anywhere Add On job

- charts/synthetics-minion/Chart.yaml
> Updates Synthetics Minion Chart to appVersion 3.1.12

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/templates/rbac.yaml
This PR adds new permissions needed for the introduced reflectors in the SA.
- fixes #
> [super-agent-deployment]: Add needed permissions for reflectors

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/templates/rbac.yaml
This PR updates the proper rbac `apiGroup` for the specified resources.
- fixes #
> [super-agent-deployment]: Update rbac with the proper apiGroup

- charts/nr-k8s-otel-collector/Chart.yaml
> [nr-k8s-otel-collector] update chart to not use beta version

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-minion/Chart.yaml
> Updates Synthetics Job Manager chart to release-380, minion to 3.1.13

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No.
Updates Node Browser and Node API Runtime charts to release a new version. 
> [Synthetics Job Manager] update runtime chart versions

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/templates/daemonset.yaml
> [nr-k8s-otel-collector] fix helm templating error 

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/README.md
No
This clarifies on the README of the logging chart that we can also run the commands for upgrade the chart.
Just a README change
> [newrelic-logging] Clarify the upgrade path for logging chart

- charts/super-agent-deployment/Chart.yaml
- charts/super-agent-deployment/README.md
- charts/super-agent-deployment/README.md.gotmpl
- charts/super-agent-deployment/templates/_helpers.tpl
- charts/super-agent-deployment/templates/auth-secret.yaml
- charts/super-agent-deployment/templates/deployment-superagent.yaml
- charts/super-agent-deployment/tests/auth_secret_test.yaml
- charts/super-agent-deployment/values.yaml
no
This PR introduces a new configuration option for managing authentication secrets within the Helm chart:
1. **authSecret Configuration**: Added to the values.yaml, allowing users to specify and create an authentication secret.
2. **Helper Function**: Ensures auth_key is provided when authSecret.create is true, preventing misconfigurations.
3. **Deployment Template Updates**: Includes the new authSecret in the deployment, ensuring it is correctly mounted.
4. **Helm Unittest**: Added test cases to validate the correct creation, mounting, and error handling of authSecret.
Please review the changes and let me know if any adjustments are needed
- fixes #
[Place an '[x]' …
> [super-agent-deployment]: add authSecret configuration and validation

- charts/super-agent-deployment/Chart.yaml
> [super-agent-deployment] bump sa app version (NR-277895)

- .github/workflows/lint_test_charts.yaml
- charts/super-agent/Chart.lock
- charts/super-agent/Chart.yaml
> [super-agent] chore: bump flux dep

- .github/ct-install.yaml
- .github/ct-lint.yaml
- .github/workflows/lint_test_charts.yaml
- .github/workflows/post-release-nri-bundle.yml
- .github/workflows/release.yml
- README.md
- charts/nri-bundle/Chart.lock
- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- charts/nri-bundle/README.md.gotmpl
- charts/nri-bundle/values.yaml
Integrate k8s-agents-operator into nri-bundle
- fixes #
> [nri-bundle] feat: Integrate k8s-agents-operator into nri-bundle

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No, adds to an existing chartt
Update the SJM version in the chart, as well as the Synthetics node browser and API runtimes.
- fixes #
> [synthetics-job-manager] feat: SJM and Runtimes Helm Chart Updates 6/27

- charts/super-agent/Chart.yaml
- charts/super-agent/values.yaml
Removing defaults that are creating issues in the e2e tests
> [super-agent] Fix super agent chart

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
> [nr-k8s-otel-collector] add in top level prometheus controls for ksm specific pipeline

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
No.
Update Node API Runtime chart to release a new version.
> [Synthetics Job Manager] update runtime chart version

- .github/workflows/lint_test_charts.yaml
- .github/workflows/security.yaml
- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
> [nr-k8s-otel-collector]add resource detection processor for host entity synthesis

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/README.md
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
- charts/nr-k8s-otel-collector/values.yaml
> [nr-k8s-otel-collector] low data mode default to true, add host metrics to ldm

- charts/super-agent/Chart.yaml
- charts/super-agent/values.yaml
no
This pr bumps the Sa image version
> [super-agent] bump image version

- charts/synthetics-minion/Chart.yaml
> Updates Synthetics Minion Chart to appVersion 3.1.17

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
NO
Update Synthetics Job Manager Helm Char with latest version of SJM and the browser runtime to support Firefox monitors. 
- fixes #
> Synthetics-Job-Manager: Synthetics job manager + Browser runtime release

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/values.yaml
Image pull will work once gating feature gets in to prod (and pull permissions are reinstated).
- fixes #
> [nr-ebpf-agent] Update client/agent tags to latest version

- charts/super-agent/Chart.yaml
- charts/super-agent/values.yaml
> [super-agent] chore: bump sa image tag

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/templates/otel-collector-config.yaml
- charts/nr-ebpf-agent/values.yaml
No
This PR contains updates to the helm chart for upcoming LP. Specifically, we update the client to export `http.route` in HTTP metrics to light up the transactions UI, disable JVM stats tracing since we do not export that data and modify the collector to synthesize service<>service entity relationships.
- fixes #
> [nr-ebpf-agent] Update the helm chart for LP

- charts/super-agent/Chart.lock
- charts/super-agent/Chart.yaml
- charts/super-agent/charts/super-agent-deployment/Chart.yaml
- charts/super-agent/charts/super-agent-deployment/templates/_helpers.tpl
- charts/super-agent/charts/super-agent-deployment/tests/configmap_superagent_config_test.yaml
no, recreate of this pr: https://github.com/newrelic/helm-charts/pull/1476 
- fixes #
> [super-agent] fix eu URL

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
Fixed typo.
No
Fixed a typo in README.
- fixes #
> [nr-ebpf-agent] Update README.md

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
> [nr-k8s-otel-collector] standardize host receiver w/ rest of NR and add cumulativetodelta processor

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml
- charts/nr-ebpf-agent/values.yaml
Enables configuring where data gathered by the eBPF agent will be sent.
- fixes #
> [nr-ebpf-agent] Add helm chart field for OTLP endpoint

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/values.yaml
> [nr-ebpf-agent] Upgrade ebpf agent/client image tags to 0.0.4 and 0.0.5 respectively

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
- charts/nr-ebpf-agent/values.yaml
~This PR has a hard dependency on updating the ebpf client version -- need cut a new release for that first.~ Done in #1493 
No
Adds option to configure push period from the ebpf agent. The eBPF agent applies a request path clustering algorithm to reduce cardinality in exported HTTP data. The algorithm only looks for similar request paths within data of the same push period. This change enables customers to increase the window under consideration for cardinality reduction if needed.
- fixes #
> [nr-ebpf-agent] Add option to configure push period.

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/values.yaml
No
Bumps the eBPF client version.
- fixes #
> [nr-ebpf-agent] Bump the eBPF client

- charts/newrelic-pixie/Chart.yaml
- charts/newrelic-pixie/templates/job.yaml
- charts/newrelic-pixie/values.yaml
No
Templates the default cluster-registraton-wait image.
- fixes #
> [newrelic-pixie] template the cluster registration wait image

- charts/super-agent/Chart.yaml
- charts/super-agent/values.yaml
> [super-agent] chore: bump image

- charts/nri-bundle/Chart.lock
- charts/nri-bundle/Chart.yaml
> [nri-bundle] update KSM

- charts/super-agent/Chart.lock
- charts/super-agent/Chart.yaml
- charts/super-agent/charts/super-agent-deployment/Chart.yaml
- charts/super-agent/charts/super-agent-deployment/templates/rbac.yaml
no
add persmissions to agent control to create apm resources 
> [super-agent] adding permissions to act on newrelic resources

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/templates/_helpers.tpl
- charts/newrelic-logging/tests/endpoint_region_selection_test.yaml
> test: added test cases for endpoint selection for Metrics endpoint

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
- charts/nr-ebpf-agent/templates/otel-collector-config.yaml
- charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml
- charts/nr-ebpf-agent/values.yaml
This PR bumps the eBPF agent/client and the helm chart configuration for the OTel collector.
- fixes #
> [nr-ebpf-agent] Bump eBPF agent, client, helm chart

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/templates/otel-collector-config.yaml
No.
Adds the APM filter from the upstream chart. 
Automatically detects pods where the APM agent is installed and prevents the eBPF agent from also collecting data from that pod. This will reduce data duplication, ingest overhead. 
- fixes #
> [nr-ebpf-agent] Add APM filter.

- charts/super-agent/Chart.yaml
- charts/super-agent/values.yaml
no
bumping super agent release
- fixes #
> [super-agent ]BumpsuperAgent release

- charts/super-agent/Chart.lock
- charts/super-agent/Chart.yaml
- charts/super-agent/charts/super-agent-deployment/Chart.yaml
- charts/super-agent/charts/super-agent-deployment/templates/uninstall-job.yaml
no
To garbage collect secrets after the disinstallation
> [super-agent] Secret garbage collection

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
No
Update the SJM from release-404 to release-418 and Node Browser Runtime from 3.0.7 to 3.0.12
- fixes #
None
> feat: [synthetics-job-manager] Update the SJM and Node Browser Runtime Chart yamls.

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml
> fixes #NR-348247  [nr-ebpf-agent] helm-charts support for Otel proxies

- charts/super-agent/Chart.yaml
- charts/super-agent/values.yaml
no
Bump the super agent version
> [super-agent] Update super-agent version

- .github/workflows/post-release-nri-bundle.yml
> [nri-bundle] feat: Add eks-hybrid-nodes support

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
> Update the SJM and Node Browser Runtime Chart yamls.

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
> Update chart and appVersion for node-api and node-browser latest release

- scripts/write-release-notes.sh
> [nri-bundle] fix: Add K8s Agents Operator to nri-bundle release notes

- charts/nr-ebpf-agent/Chart.lock
- charts/nr-ebpf-agent/Chart.yaml
No
Bumps the common library to 1.3.1
- fixes #
> [nr-ebpf-agent] Bump common library

- charts/agent-control/Chart.yaml
- charts/agent-control/values.yaml
> NR-359076-Change-Otel-collector-example-from-0.2.0-to-0.1.0

- charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
NO.
Removes selector labels that we don't need. 
Installed the chart without the new selectors and got data: 
- fixes #
> [ebpf-agent] Remove unnecessary selector labels

- charts/nr-ebpf-agent/values.yaml
NO.
Updates the images to match what they should be for the release. 
- fixes #
Released images can be found here. 
https://hub.docker.com/r/newrelic/newrelic-ebpf-agent/tags 
> [nr-ebpf-agent] updating images for deploy.

- charts/nr-ebpf-agent/templates/_tls.tpl
Commenting out use of lookup.
- fixes #
> [ebpf agent]

- charts/agent-control/Chart.yaml
- charts/agent-control/values.yaml
> bump release-0-31-0

- charts/agent-control/Chart.yaml
- charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
> NR-361437-fix-jd-parse-error

- charts/agent-control/Chart.yaml
- charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
> fix concatenation error message during l2 identity

- charts/agent-control/Chart.yaml
- charts/agent-control/values.yaml
no
Bump the version of the AC image
> chore: agent control release-0.32.0

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/templates/_helpers.tpl
- charts/newrelic-logging/templates/configmap.yaml
- charts/newrelic-logging/tests/fluentbit_monitoring_config_test.yaml
- charts/newrelic-logging/values.yaml
No
This PR attempts to add additional labels to prometheus remote write output plugin that will facilitate entity synthesis
> [newrelic-logging] Enable fluent bit entity synthesis

- charts/agent-control/Chart.lock
- charts/agent-control/Chart.yaml
Bump dependant chart
- fixes #
> [agent-control] deps: Bump Flux chart version to 2.14.1 (NR-366630)

- charts/agent-control/Chart.lock
- charts/agent-control/Chart.yaml
- charts/agent-control/charts/agent-control-deployment/Chart.yaml
- charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
- charts/agent-control/charts/agent-control-deployment/tests/preinstall_job_test.yaml
- charts/agent-control/values.yaml
fix the value name used for pull policy
- fixes #
> fix: use the correct pull policy value

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/templates/_helpers.tpl
- charts/nr-ebpf-agent/values.yaml
No
Modifies the logic such that metrics are enabled by default when a protocol is on.
- fixes #
> [nr-ebpf-agent] Update protocol enablement logic

- scripts/write-release-notes.sh
> feat: update release notes script to support eBPF

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml
- charts/nr-ebpf-agent/values.yaml
> [nr-ebpf-agent] Adding support for EU

- charts/agent-control/Chart.yaml
- charts/agent-control/values.yaml
> [agent-control] chore: bump AC to v0.33.0

- charts/newrelic-logging/Chart.yaml
No
This PR is meant to re-run the release chart workflow from scratch.
> [newrelic-logging] bump chart version to re-run release workflow

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
> [nr-k8s-otel-collector] fix: Fix daemonset collected metrics

- charts/agent-control/Chart.yaml
- charts/agent-control/README.md
- charts/agent-control/README.md.gotmpl
Adds Flux related docs
- fixes #
> [agent-control] docs: using existing Flux

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/templates/_tls.tpl
- charts/nr-ebpf-agent/values.yaml
No.
Bumps the agent and client.
- fixes #
> [nr-ebpf-agent] Bump the client & agent

- charts/agent-control/Chart.yaml
- charts/agent-control/values.yaml
> chore: bump AC 0.34.0

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
> [synthetics-job-manager] update synthetics job manager version

- charts/newrelic-logging/Chart.yaml
- charts/newrelic-logging/templates/_helpers.tpl
Updating the scrape interval to 1 minutes to reduce the ingestion of Metrics due to Fluentbit
- fixes #
> ci: Updated Fluentbit scrape interval

- CODEOWNERS
- charts/pipeline-control-gateway/README.md
> Adding codeowners for pipeline-control-gateway charts

- charts/agent-control/Chart.lock
- charts/agent-control/Chart.yaml
- charts/agent-control/charts/agent-control-deployment/Chart.yaml
- charts/agent-control/values.yaml
no
Updates the version and removes the beta suffix so that the chart is not hidden anymore
> [agent-contorl] update version for PP

- charts/pipeline-control-gateway/Chart.yaml
- charts/pipeline-control-gateway/values.yaml
> update pipeline control gateway version to 0.9.1

- charts/pipeline-control-gateway/Chart.yaml
- charts/pipeline-control-gateway/values.yaml
> update pipeline control gateway version to 1.0.0

- charts/synthetics-job-manager/Chart.yaml
> updated SJM version to 438

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
> updated synthetics-node-api-runtime version to 1.2.113

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/README.md
- charts/nr-k8s-otel-collector/README.md.gotmpl
- charts/nr-k8s-otel-collector/values.yaml
> [nr-k8s-otel-collector] feat: Use NRDOT + update docs

- charts/agent-control/Chart.yaml
- charts/agent-control/charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
- charts/agent-control/charts/agent-control-deployment/templates/rbac.yaml
- charts/agent-control/charts/agent-control-deployment/templates/uninstall-job.yaml
no
improves the way the delete jo is created and managed. IT remove the dependency on the main service account
> [agent-control] multiple improvements of delete job

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/README.md
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/templates/daemonset.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
- charts/nr-k8s-otel-collector/values.yaml
> [nr-k8s-otel-collector] feat: Enable feature gate for in kubeletstats + 1.0.3 Collector

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
> Updated appVersion for node-api and node-browser and SJM latest release

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/values.yaml
No
Bump the agent version to pull in a change reducing excessive logging.
- fixes #
> [nr-ebpf-agent] Bump eAPM agent version

- charts/agent-control/Chart.yaml
- charts/agent-control/values.yaml
This PR bumps the agent-control chart adding the latest released image
- fixes #
> [agent-control] chore(deps): update image to latest 0.36.1

- .github/workflows/run-makefile.yaml
- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrole.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrolebinding.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/secret.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/service.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/serviceaccount.yaml
no.
Adds missing args for helm add in render workflow..
- fixes #
> [nr-k8s-otel-collector] Fix Otel Render Workflow

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/README.md
- charts/nr-k8s-otel-collector/README.md.gotmpl
- charts/nr-k8s-otel-collector/templates/_security_context.tpl
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/tests/config_map_test.yaml
- charts/nr-k8s-otel-collector/tests/gke_auto_pilot_test.yaml
No
There's some configs in our public doc that are needed to run in GKE Autopilot but are not documented in this repo. 
Instead of adding the documentation here, this PR just makes the gkeAutopilot config in the values.yaml do all of the necessary setup to run this chart in GKE Autopilot.
See our public docs for GKE Autopilot configs. 
https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-otel/#install
Before changes
After changes
Also removed '-' from some unit tests since it's randomly failing both locally an on github... 
- fixes #
> [nr-k8s-otel-collector] Better GKE Autopilot support

- .github/renovate.json5
- CODEOWNERS
- charts/agent-control-deployment/.helmignore
- charts/agent-control-deployment/Chart.lock
- charts/agent-control-deployment/Chart.yaml
- charts/agent-control-deployment/README.md
- charts/agent-control-deployment/README.md.gotmpl
- charts/agent-control-deployment/ci/test-values.yaml
- charts/agent-control-deployment/templates/_helpers.tpl
- charts/agent-control-deployment/templates/configmap-agentcontrol-config.yaml
- charts/agent-control-deployment/templates/configmap-subagent-configs.yaml
- charts/agent-control-deployment/templates/deployment-agentcontrol.yaml
- charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
- charts/agent-control-deployment/templates/rbac.yaml
- charts/agent-control-deployment/templates/secret-sa-auth.yaml
- charts/agent-control-deployment/templates/secret.yaml
- charts/agent-control-deployment/templates/serviceaccount.yaml
- charts/agent-control-deployment/templates/uninstall-job.yaml
- charts/agent-control-deployment/tests/auth_secret_test.yaml
- charts/agent-control-deployment/tests/configmap_agentcontrol_config_test.yaml
- charts/agent-control-deployment/tests/configmap_fleet_configs_test.yaml
- charts/agent-control-deployment/tests/deployment_agentcontrol_env_test.yaml
- charts/agent-control-deployment/tests/deployment_agentcontrol_securityContext_test.yaml
- charts/agent-control-deployment/tests/deployment_agentcontrol_subagent_configs_test.yaml
- charts/agent-control-deployment/tests/licenseKey_test.yaml
- charts/agent-control-deployment/tests/preinstall_job_test.yaml
- charts/agent-control-deployment/tests/rbac_test.yaml
- charts/agent-control-deployment/values.yaml
Yes
[NR-383600](https://new-relic.atlassian.net/browse/NR-383600) (internal)
A follow up PR will remove the current sub-chart and reference to this on `agent-control`
[NR-383600]: https://new-relic.atlassian.net/browse/NR-383600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [agent-control-deployment] Extract agent-control-deployment from agent-control chart

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
> Add extra metric needed for LDM

- charts/agent-control-deployment/Chart.yaml
bumps ac to latest release
- fixes #
> [agent-control-deployment] chore: bump ac version

- charts/nri-bundle/Chart.yaml
- charts/nri-bundle/README.md
- charts/nri-bundle/README.md.gotmpl
- charts/nri-bundle/values.yaml
NO
Just some small README fixes for the nri-bundle chart.
> [nri-bundle] fix: remove (Preview) from k8s-agents-operator & other docs things

- charts/synthetics-job-manager/Chart.yaml
> Updated appVersion for sjm

- charts/agent-control-deployment/Chart.yaml
> chore: bump agent control deployment chart

- charts/agent-control/Chart.lock
- charts/agent-control/Chart.yaml
> chore: bump agent control chart to 0.0.66

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/ping-runtime/Chart.yaml
> uptick charts and ping run time version

- charts/agent-control/Chart.yaml
- charts/agent-control/templates/install.yaml
- charts/agent-control/templates/uninstall.yaml
no
Removes some conditionals that were included in the previous PR to avoid issues with `ct` tests.
> [agent-control] remove unneeded conditionals

- Makefile
- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrole.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrolebinding.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/kube-state-metrics/clusterrolebinding.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/kube-state-metrics/deployment.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/kube-state-metrics/role.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/kube-state-metrics/service.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/kube-state-metrics/serviceaccount.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/secret.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/service.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/serviceaccount.yaml
No
The rendered files were full of names like "example-nr-k8s-otel-collector" 
And tags that included "example".
This removes the "example" from the rendered files giving a more polished chart for those choosing to use the pre-rendered files. 
- fixes #
> [nr-k8s-otel-collector] Fixing naming for rendered files.

- charts/agent-control-deployment/Chart.lock
- charts/agent-control-deployment/Chart.yaml
- charts/agent-control-deployment/tests/preinstall_job_test.yaml
- charts/agent-control-deployment/values.yaml
> chore: bump AC version to 0.40.0

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrole.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrolebinding.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/secret.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/service.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/serviceaccount.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
> [nr-k8s-otel-collector] fix: Missing k8s.volume.name attribute

- charts/agent-control-deployment/Chart.yaml
- charts/agent-control-deployment/templates/preinstall-job-register-system-identity.yaml
no
Removes unused default values.
- fixes #NR-424486
> [agent-control-deployment] remove unused default values

- charts/nr-k8s-otel-collector/Chart.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrole.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/clusterrolebinding.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment-configmap.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/deployment.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/secret.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/service.yaml
- charts/nr-k8s-otel-collector/examples/k8s/rendered/serviceaccount.yaml
- charts/nr-k8s-otel-collector/templates/daemonset-configmap.yaml
- charts/nr-k8s-otel-collector/templates/deployment-configmap.yaml
> [nr-k8s-otel-collector] Remove newrelicOnly

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
> Update Node API runtime to 1.2.120

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
> update node-browser to 3.0.35

- .github/workflows/nr-k8s-otel-e2e-external-test.yml
> [nr-k8s-otel-collector] Test external PRs

- .github/PULL_REQUEST_TEMPLATE.md
- fixes #
* Updated the default PR template to include the release notes block.
> feat: Update default PR template

- charts/agent-control-deployment/Chart.yaml
- charts/agent-control-deployment/values.yaml
no
Update versions for release
> [agent-control-deployment]: bump up versions

- charts/agent-control/Chart.yaml
- charts/agent-control/values.yaml
no
Bump up versions for release
> [agent-control] bump up versions

- charts/agent-control-deployment/Chart.yaml
- charts/agent-control-deployment/README.md
- charts/agent-control-deployment/templates/_helpers.tpl
- charts/agent-control-deployment/tests/configmap_agentcontrol_config_test.yaml
- charts/agent-control-deployment/values.yaml
Adds custom chart repo urls helper
> [agent-control-deployment] feat: add custom repo url config (NR-436882)

- charts/agent-control-deployment/Chart.yaml
> [agent-control-deployment] bump version

- charts/agent-control-deployment/values.yaml
- charts/agent-control/Chart.yaml
- charts/agent-control/README.md
> [agent-control] bump version

- charts/agent-control-cd/Chart.yaml
- charts/agent-control-cd/templates/flux-validator.tpl
- charts/agent-control-cd/tests/flux-validator_test.yaml
NO
This is moving the flux-validator to he agent-control-cd.
- fixes #
> [agent-control-cdl] feat: move flux-validator to umbrella chart

- charts/synthetics-job-manager/Chart.yaml
> uptick SJM to release-451

- charts/agent-control/Chart.yaml
- charts/agent-control/templates/install-flux.yaml
- charts/agent-control/templates/install.yaml
- charts/agent-control/tests/install_test.yaml
- charts/agent-control/values.yaml
Leverages the latest changes in Agent Control to create Flux resources as a HelmRelease CR.
The contents of this PR will also need other additional changes:
- Bumping the AC version in `agent-control-deployment` to one that includes changes in the CLI: #1851 
- Add Flux uninstallation functionality.
This PR this is targeting a feature branch (`feat/flux-self-update`) to control the merge happening when everything is ready.
> [agent-control] feat: install Flux itself as a HelmRelease CR

- charts/agent-control/templates/install-flux.yaml
- charts/agent-control/tests/install_flux_test.yaml
No
Enables authentication when adding the Helm repo for the Agent Control CD. Previously, the configuration was hardcoded and did not allowed setting up auth.
- fixes [NR-447488](https://new-relic.atlassian.net/browse/NR-447488)
[NR-447488]: https://new-relic.atlassian.net/browse/NR-447488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [agent-control] fix: add auth mechanisms for Flux helm commands

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
> node-api Version update-1.2.126

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
> node-browser Version update-3.0.43

- charts/synthetics-job-manager/Chart.yaml
> sjm Version - 463

- charts/nr-ebpf-agent/README.md
- charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml
* Updated eBPF data reporting to otlp.nr-data.net:443 by default.
> fix: Updated eBPF agent data reporting to otlp.nr-data.net:443

- charts/nr-ebpf-agent/Chart.yaml
- charts/nr-ebpf-agent/templates/_tls.tpl
- charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
- charts/nr-ebpf-agent/templates/otel-collector-daemonset.yaml
No
- Added an annotation to monitor the certs secret that would eventually restart all the pods.
- fixes #
> [nr-ebpf-agent] Restart all the pods if certs secret is updated

- charts/agent-control-deployment/Chart.yaml
- charts/agent-control-deployment/values.yaml
> [agent-control-deployment] Fixing typo in example

- charts/agent-control-cd/Chart.yaml
- charts/agent-control-cd/values.yaml
> feat(flux): bump flux chart version

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-api-runtime/Chart.yaml
> node-api version update -  1.2.134

- charts/agent-control-cd/Chart.yaml
> [agent-control-cd] update release version

- charts/agent-control-bootstrap/Chart.yaml
> fix(keys): bump version

- charts/synthetics-job-manager/Chart.yaml
- charts/synthetics-job-manager/charts/node-browser-runtime/Chart.yaml
> node-browser Version update - 3.0.55
